sprite $c_role [128x124/16z] {
xPhNikGW34HDplJ_V-tcdRektK3RZ3QUTy-XYhOO2Hz_Blyn8KN_o-n-u1lT_XBxn8FXjUrXuiHKNK64P0PbkoHgs1FU8JrPRWe4UYim5GiKynoxRH3ehS1s
45Ixr-uwIBhRNMX_rGhy1CNUiXn0iBqeHjnb1ZNxvhASi8sqkT3o9BRGRgSOhj3kfowjm7GyZKg-x_kn7-Wzdim7Uu1dCxXtVZ_kFV-4G3E31WgyutSGg2Om
Gm6lklsIhFhsIUQRUWkMcSl604PmZFZjgRch1dSmj4UGVD_pV-XwX-4grkctgy_CHZoS9rQvUVRr-4PynhqALCXjb_Y65SBrxI_s4D11gCJsYssNy46uTFZq
81_9fMJ_QX3u06IsR8OVcY4MPguSGOFq5pmef3_JyPF-363Mb3i0PCu_Bnm-KwQbciTym5D-79B8-HlGNYobStuh_OtocvS_KW4OoX-b7vJV0_tKCmNAtuNU
SFu8j5CM8bVAXD_Vz2VXvofG8VpMkGoCz9C283jd2ByeMI3y7QzI27zLy3C1SAf-6O2axNV4uSFxwIu8r_ozZel-INS-qZ_SwTmezCyzYBp_iOT5-XtR1JNg
WNuQvJZfZsmNnFNj_NI8MEdFP1TakBwzdzxXAFqD2x2TJnF-RqNKJkcVMC2mdO_meyUG0U6tR1SqiO9VhJ-97SHXYRBgxrY27hij-YtR1YUi4TVyXPt43gmn
blo67iHXbR3Yp-mWphB3SnzVnR4pP55zTbnZLNeI7AdPtSOB5Ci_qZ_GcybFmitbwR6aWK2KNx9iI_Abcn2_QtuVBrv4D32uFVfq-U8XxBWyQpSkdjB2Yy-E
SoYQw9_j08MvUVCOHV1lPgY2OmGnYRotWGCFg3cyIHCaRTVbPukfRxk3Tb324FL3zGQyGe5ulCrGlN-N6Dtl7oHEDtkIg9izITNDdcJePa-Ycps9rSsU9EX-
UoKfkjcJT6od70mAsTFDu44I5BAdby5my7JTx4acDj6FIrZTx4c2RlOaMJTxagwRFSdScptz31utyHkpfvz1VzodxVtKawTfH7z_Jp3TiGqNCqcmnn_0Vpu3
}

sprite $cm [128x124/16z] {
xTe7TkGm30DGKkwoBDp_jDjRfk1P6OFQzYz0vGr2kDcVwp-VbdcqNiO3NvJKPNh53yTemQQADshe2MRSgrFmz7kp1LX0BARb6mZr2JpZXCrD8kqWr2T81Gro
iaiD1OtASFMYxNM2iQB9jMjvmYlg95XrOIUOSObPi6ZRB895gpo1PrnkyuP5Av7TJl02cTpm_wwHZ1iXvaP1xJ1cWTnWH0MXpw0Z09a_WD4dS4M0aVxyUgiz
XGZLdaa8qNYzKV9t1L_j-QIZRGSNF3BTBUTa9wrjrqE8cL_ezj7F1-a-xNo-WRQe-HFx-VNvHzQN3yVBHy_xb0-le0ECle8Gf_BoqIFbeyChQ8SQho0Gxrr7
1vue3TldXNMydW_063lVIVc8vlCAGkpyt7a-IFbeyiy3i23OGCgdGmKXMkNbeyVBHo-HyWcl8CGhl7pqMFdezm_Wf7m4-vTLK9NFvnM47lF1oqS_tsdvwESF
T-KZop-l8FHHUVdeyUsZvxJyzDBlyVSxEg7hLozRtm0wkVovwlaRiHWfGCNpnxTsTlUjdr_jZI5wljjRYtu-VmkP8-SlTk-8o__Uz_dpONqVG3jx_zNp3NWE
lV4Z6HJAHdXSzZfbq8sRzTdZiZvxtA7F7gVF7fVqsUCc_HClRjDdZokut6OjTDdhb45hD8coroU3axKh-knnLV2ejqi6xPqcVVQuLPyzhkYpnrLjzlGPj1UD
mkpfCpZQwtR1fvvDTddq9VS4TR3B3FFQQ4hs1_Zl8m
}

sprite $crb [128x124/16z] {
xThdWkCW30HWKMqmbjx_QQ-tsUAWR9Xh-_szaiICDP1O_bxlGjbg5a2KJ_jYH16-hFR3cOMig07DGbJjEItyLpTKXM2p2vki5Pe1xZi8tIQq84l4mm3t7SHX
3ZtAGwLXJYCzUj1Itm4EMfV7ZkLYRw5bmQYZlODg3r4N35gVRS6WzTaM35gV5Xo3TeaUP48OjanttEzhHBcMRR4Wbsorat3FNqfoGGsmCnYCG0181kW9t8qW
qvSVxVIx3wcy9Xg5Ox_1dS73A2fz-T7WJn_aw3xc16f6KkZBZpf_-H6_V51mb0-jWau3z0eo7hstVBJjjVoaziaeFzMzsupxogUbbvQi2yh7NHLqs0r7502l
x_o-flgNlmc0rtT_cE6UFbKyho_D6u0y-UbptNxwch_jfvecznB1zuR7zBSIkiaNGNqLD3Emajg4CquSvRhhzGzNGMYOsCoxogVuJWV7H9y4py4tEC_6-VP7
Iexo6K__Idv9VRgwTcNtBd-ujN-8J_j5voiethxva-FrRM84OFdmNp_Ep-k-uFhZG3TZvyy6bW_Z_aDOFepvWmAK3td-OWMf6QD_KCVuCVeNOVamzXyeGFam
zbyeOVaySl_PNQSW0mlttqXnS3BE7yZ_lOksxTRvIsrQWFBZY_3v-GAq3n-CNxuEzSSNOFj3jmaK8Dk1fsys5P3uYuyseqhoLETd3vtqxA5WWFyRTE9d3rL-
zb2d__p5ps2N2u6VFPJusKELdptK-Tb39pzxY9yz5FdPGuN_x1LghEmHdqHeua787ZU3ubG8sUDbi8ZVu6SFwPe7NlWPb3iLVlRGpiyU6lpi8QLd3qL-zb1U
a3rU1hEytR7WKK-NWn3z1MS2JV8mgUvE9SfVuDr7
}

sprite $crd [128x124/16z] {
xPfLkcGX48CBTsh_gnsNgpM4BiuP-r-l13xI2TBqv_8V4rBqT1T-y1UwlKLzyW-6fui9avynFLr8vDVCS8lwKo9TG6A1H6SnXGLEZy1KNg0OEe9jB71w1BOp
GBMaYkiCqfrsqDur0ZyPGZUM0mEeXsBaHvb1MHqdAWSjJb8EMfo41gqwnM11gqyrj83fV8mAVjxriIJZ-J26H1XWjjePPMXzvgkZp_ZE68u49g_YwJjPpuC6
dmKUb8A-sukpfkN0p6jCUTWo_l7bp_ISmG2PtcLt2eK19hs7XTotxS37zniMq0Sok5-Z7w7brzVlKFhew_D6z_Nsb9VweJrbR2PGqJf7c3XP8c3BNmd63Bo2
Z60N6CiIKFau_TE30Sfdq1O6hg2nk_fubsN0VeNs6605MMrzq81HMn-ieAQj3rOGQ-jZ5MJqzI43U7Lzh8AAkZvMGNojVhrPduNoqT97392krdUhlztyPwos
VaQtliqJH8YVoNsfWYmlK5MVBJPEFbtp8jMAvQEw5ybY1U47NnKlzfsJJrDyHDYwzQCzX0J2xW-itWA4xMitd2wRcU-OFmlbexx-eW4Id_Q_N47Z-FBB5NHw
-ack8CkB3AFxX0ccJpVANramKFa5Wd3-Cx7o-zYL-RVu6My8P2pVX1jWewIgByRlUVqgr9-slbo0xOG-yeOoT_Ij3u8j1v9b1jTFNmMw5_I19nnGtuudDb8u
Vr62zEslj-K3V8MiYFxafrHOFwt_GLxOq3jGlm4tfddXRhDY-WDv_SmhluZf6-JzgmY_9_t72NXFyc1VsSzOuFuxWg5f5_JT-bjYHM_jsuw-cOZtP0zcND_q
1UyjUx0vK3yCs7jo3evMdl1wShKyeKt0Uu87zQcq0fzYG6zt-XZamAAFfLKA7o121rPr2Y6SyzvD7YIGSCXxztWm44xNzHxEP2Kw8UXxa3O9kjx3oRhUm-cw
tiEPQjwxoOFq85x9U_TuqDFZDDucamPDr_euaNUOZjHmCOC4Ity0__a8
}

sprite $cronjob [128x124/16z] {
xThbekCu30LWcTdd_Pzs8RFa2vQLLktIzslcqabgHGhHFzV_J4ZHqxluWKktRqcV-CFmz69XOZ4zlL34PpEyC_qIwGKIDXBfCWMCf9bUSQ0OKc4R69fRO3i4
ggMdSXr2tJsxqRvh2_o4o7FRSi0nXQOOyQWPbDDvKQ7HoYI5HYkJ51gjJ362HgkY6ZfWEjHKjUEz-TN0ropjUTnJQDNn3MODe9q_Q2UfvyFHnjJCvslGG3yV
ctodcizNO7v5lcUMNpi_CqUVTlwaxrZLVBu0ese-tuFxQ_8Zi_pQ-PtfFjhvO6UVt2Yh2OWxKC6B16RvjLLc-TKnmqUTOOQF0du43RnCFYg_61OPbnmM4PTY
LWCxysZuq2fyUV0OflyS5s1KpUT7K7iityLSQgib1NkG7vdb5-QlPlLSVcUwZpn_DSKToD_CTtz4zf9JIhcDMnsetCkFk8paw0ycLFa8WYX_lLQlL_WYJNO4
FPvlhv1cxrnAiiE7ptVB_p-nNL00IPv_xVsmTEzooj5YYFEl5jyDxSJZ4GHnVWFGYH4FHv0LvqS0mz06imJyTkQqgBZKTFbZYZ3QqGXgQlTrpJpvRJ3EPeXp
pXpVqElIKr_-HjBNtQ3p1U0Xr-Wmt_CTg43Ed-RJO4VGXDYau_p4ZY1yAQugBZd6221p-NnrCLS-y-lTy3_-e3_Ffy4KG1BcUm0ao2_C0JI4-GaOalp8Z208
ypFG9Fb-7s2b-GKeadotBq2ldM_t7IXAy_Ft-LcIRxdzb-UZM_7-6sb-0EhtipvBrv-cCDy1O_EeVWPQHQO1Us4-0TYURxLr4J8t09imlmDkUzQ_raTd7mbF
MNxQFL2EFnR1CVEdRKOKbs-1pZqxD_lbdxHmelaRv_xarmyavkCtZpvvBBGJcQFlS_bK21awKvdQktl_iT8HnzJU_PDmJoV6yJDe1vbfY9S5AnSXquWLcDfx
h0RhdSMFp69952PUkiq6GatwuGzkYoNsDu3AdQuH8LKaBmqwSRlYpKoVk7RxbiM0N5bwaKtZaPQ9MrgEtZiVKXtCkpSS2oM6pWIei7IgG46aSnrFLqW2ppQ8
eLo391GKQ-_rDHX8hklM7c_YIJenb6kGRWgwjSVBkhN7wxgrnvkwjQTVW_GWhrXx-ZNewN4DjsLwXgPR-ho8EwQZft4n2mLB_m3_-na
}

sprite $deploy [128x124/16z] {
xPfNjkCm34EfQbkD-r_jzAwJ9y2XusdtFrQ328gC_BdynwKjHxcBsFKJpTyo-j1lz2Wl9WtzYH7bXMIT6Ud5eyzaUG6Rli4cr-8ENR1TENfHWCF99VYg05VD
m3SbA5vC2Kr9Mh0Ej7VD80wbi0tBIPzX98DGTziCifgGZGCjpsOSQ7asDj2QSpWkqDfJd02uffTHoFjkpyeNebxCuWpqQZftv-q9yWP32Umrw1HajB9_uAXD
QUGnGG7Q5frynwTZM2bmNm-UdSo4Gt7Y-UElZyMJXuBiyX0YeJe_Wo6Fy40YOU1Qf_ADwjXKaO_1JHzoY9YPL-QFFmaAuDsDZZvHS00HiDwNXA6SZK07ULwO
ZF3r0DA3SEEK1JbSBIuVRQZgg7iyOoEC-SotDRMVzyVJFk9myzdcnp2GsFOJ5jIXTAb0YeedB0ZviE-WI2jjGHvOlX-0ff4DGCqdunVhO8A01mCt-irPgPcr
eFMQTifNIGjootlY0L-35OYP3-ci2Nz8EiHywhnyV0CyPq7BC76mcTMWB6Xv_8D8hNa1XDLol08q_BeuuE6BtsV-5s5jFcDQ3IM0o5ZGClWNCF2XaNq0vWEg
gRF3pmBCwFXyUfwGkrh1_UTB6X6o8DMdzEUeuUUxwfwyJTkPWieqIpJ-u4zwFx1DErIVYx-H7rxJyjku_rJc7JIh5lcgPnCwrz5W7I2JgcH6t-1dy0OSAwt0
XbTYEvPJxqn2Kubi0SqIEfxH5bqp5XlBlJyyExpgsgWxVg6F-Qw20ipuiVgEdDNEDMCYqwuewxFQo4guewmbzeK2iw9CuPUflym4ie5M9ll3wq-bZLc1tF3g
i61nm8K-H_NlDjHSCrhhpH8KfkADfmXMMdiOYZAOac42nYTnLESnOGLZd40kvc3QPRZsy9fbTORTsdgc-PdDnkz0iexqtxADzl3lbPzdaAmxu8NhlqRplmDr
hF_ypFX531hm_LF_lHXe3z2WAOufbjWJcFQTFLdMTBsC8WXw5LqW_0tQu-CQZnUKunhjuJGrvn26wxHtamQ595salNiqc8IdsMgFPwWHJHZiDIWdIRRQuzbj
jSVJRBN7CyoqTvC6vKcYaVRkqM2Kvwbwcbqig3T8t-1DC8AO4V9Eahpy0VpdFG
}

sprite $ds [128x124/16z] {
xTddjgCm30HWkLECzFvFkoLiu_WaOryOiktxV--aZAK0ykVwpwMIexnBtEoX-hUag_smHRbPKZlGA3VArj9qStehomsAlL24oyq656RwOXrc9nH-DO3v2dor
0OkNIuLgWsguUj2-wnL4jI7NZkLatGX3CTjPciZfM2OCsZ65C6Z75CAW7JExWK5BiJZfuAhHBEJpZg6z48qCV0V6je4pJnVa1JM0sq5d7NGgtrNRbOFfUr9v
cEr8dWk35PxjGPjtSPZxkRk1as4ge_dU3kAvhtyxcp-XquVpOzsfxUh1PZkjNxWcN-KPtvkVhTiX7nGmK_Fn3AxMGLDAywdyJ1s-EB-2wSFEju7Trmuzswtb
OFqv2Oz3ByMOEdVWtBKr3Z_ecidLzMRI-DSle_aol8BSRVasldn49AmFjjlM0xNT-k11lXjUFcC_pKARZrVGHit7AyZkorTfUKh-VluRmyjdNwkzwhgkpVm3
AsYrnbJ6JFfY_g8LX8y95dhpQzVqSJAgDz_0yg7dEx1ysFa9_2KxVo7cj-SF5o1ScXz41EGxEIXtvmSvsAZvU0NPtVaAbWyxty3oEPslgY_pFLW-v_8VT3-A
5TyLDbB-2nKi7tQ-oK-Ha1zZxBuJE1Fo3KdoWzwQtwuWO-RZ0WHgFYv0kJe_e_8TLz1sMRv-OK2xWWpaavuOgkmyDHyNC5BpSG7pTVdnYybw-SlVls7j_tVl
oWVZbvs_WFN7pdVWvmyvlyXFUd_-2gw-oVbAlFvguVzTy3KIvauyXLoieJaEITj0zngRtMO57nxPrddtoW_JWUxXMv0o3EIZMYztv6TvRkFdB_q7k0mRx5uh
61MUgTceWY2B4MN1DgDPf0Ttxc6Uspqi6OMNNZEtUrYroyqoWjoz-pieWnAnU_TtCCcuokqUfdQHAW2vW_91YTizRE9s3wlSxc7AxHw_Wt9I97QFty4evwts
OPDSOQLNdt9De44k4_8qA7dv0_pt6G
}

sprite $ep [128x124/16z] {
xPdfWi8s38GbNoI-zFvFsxkaNRk3jK6cr_TtWKzB1aqE-kVoFnmVAT2d24r-eRgFsBiyQO4s4xlyYRvrWYGZFMwsZoJQm4C03xA5Jm5OJy1P5ZYPJ7150DOJ
k2eAigEtugiegVxTY_PJ4uGkAjwxbgFSeKU3LMSz0RRhIGQBLiV3OD5QJi1Ptix9YaLhGcPQWAkOaHM_TniSOO8OmmGHQvhzRnxZ2T05O9z1bWq0lnU4VG8F
sK2uS_XBV46JLnntVdqdlQ3AAphz5SxSZmEOzlWTVA-zFy73R--lSFlO-mLtdxsVQSgvonzfYbZxSGMnkHy7m9lxSG0ESp-ke6RknnKaAsJ_WYOBT5m-zgZB
n_uoe8Wrk88KR-uoKWvHK6-S-WPolmyGKqhvLxtov16N3zRJSu1dRehsx9KrvJEkZlJ5xuODfgqWbJx85tzZvG1vzElrbry_WAvy-gY__9C1kZO03q4qrsTw
-UsTmm35Qo-3co1ESdtGF_t308MeAolePLfT6_NzylznW494MLT1Rl5WNVfQIYtq4wdzn3N0SfieogT-qOyRV1Y0THLK176CUkdJKwThWAQgeCNJfJOF44_E
ZqvD1V7YeU8s_GAli1N5VSJbygaq7I2FxywQFkNLyddG1VTnXJndAk1455PGNrjL7Cyk5tLOdUsCLoOL5RHoeC8nH3hElkXwN8iAirW-XSYbCjzXyqtNSsAY
zG0yi3zta0mlSzhPbYkeoNTX5BFb2f9lSoRvFXsNZpru-zZ3gFnEFw7_5abmvLdzX88gCAm_iUlWAhnUIt0We_-VF-K7wzVE3mhCq8yBiDZxiQ1lzO-lu-t-
3g-_xFsCdZpQ-pruYPaVVtZRuGUluMt-HbFyBZ-lFF_AOOByvWWJVk-_CA6Yx5talVSUHvgOamd0OaqZY1TZc319JF7qYcoVFKoppnx6FdiOPvyzJBH_w88v
xRE7gV9sJj9WdBtz6IGbqJ1x-pCOIK-rpnwcovkeXB3F87sJQ9yzp66VFKorpnwcssRFFeDqas2OFViC1hfFkNU7-Jx5FFecrmJTqzlmwL0I7Vq3-9yV0G
}

sprite $group [128x124/16z] {
xPe74jiw30N1tedxd_R_z3XwOmveYqZTwMuhcIkgqk_BFqn8qTFFmW_-HBS_nJxv6yEJCc7o3qnFYaH6Pb2s8v4KIBmWqLbCOK1l2Knb0SNG4MnZG6y9RESD
ggLRSPqtwUxkYLPp2N2YbNFlj1nOp859CVAxpA1iH-A1YNQFT62YtICTc6ZtA6PZeZr2DIJ0T3v6bMplHx6qnlDX32tXqmp1DdyKHmic0veD6cOaE_iYlZ0Z
2xzZe1jw0pks2ip2NEHO756_C_pk_fELJ4zvO_NbIKrwXfN7AWSBsFYl2hrDby_1NSSV1SD_qjyNgPpmImFmP_pY6QXe-ODW-4_wwsBu3_Y50RXJVc40MS_l
YP0XzuUKWg47JCp9o_sP266fFrz_n5GurLpx9o5Mwc_yXVPLFt2zrdwMdkoMPIO5347ejmGqcTz0nu6_CuJ-I03B_15-fl83JkRlk5v2Vu6t1qoju1S4uE_n
Hw7VmEyA_OaVI12E5_e33B_GRs6q8spO0d_Tz-Dsqk2eFSdy680J-yqttJJNxpQI-J609FQJQTSpCpVWqsi_RgXZuGTyQQruUY3KthAb3N_6uLVR_sAfLjMF
0KPzluMDIjSVOVXbVkDJQHyeoHlwHksjbkX5Vjm56QdVbS4FZE8k5pfwjk07800lywV9m4pNWdkG-GtiV902jvoH6QyNJeUJ-0DzOmhybPzIGPG4_WhvhVo5
5rGyCW8_0ZkVXT_o4WSV0VyYWBJquqUG3F-Y1p_WOEVpt9zt_G7yG8RXr_LF65iDFpRYLVqOOFnPVYjVVv-NVAezFsBbwsy4_dtauqzJrOyJiDVrumwmwVhn
N6Ng-nizO7xoyJSvRR-1ysfLlwChLTEV21aAVcWF6Znm_qbwLytnmVjls1uI9Pt8sVzDRB3VV_yrRWrMk_l-SzqShPcTUGthotPHZWzZ1BqSGDvpvOD4qOHn
Z4eIT9-zGQnkUqZW8rYIKdJRGphVJg4T5DhJRP0s2GhjwJKOQ9-kqPxAmtYT0DK6wKM2Rdj8rcqFwRhj8VD0UweDqflu0-tfDUZfVHg_JAOxQ0hf7pWdc8vk
myMyIR3q6_2F_m4
}

sprite $hpa [128x124/16z] {
xPc9ZkiW34LjjYHi_l-_VMf7BsfqKmATuBSUQRHrESvmiK6bFvV_i5-2er-5A_8acrzYhx9J72dZgnoegXK4GQfNjYE155YamK9puKq0lGeuIWSRqnHC4a2l
0fDbW6ZeLcoMGRAzkz6gLO2DTeXxsxANxr3zX5OtM86o7GaJ6kqOouH6ExC2Zd8x6myqsYb4fWuuopJYm7wVWw4sJYR3r4HcKnJsV1DB3Qe0cXbaKQ3XjmAe
9d0L1TpWygVuCLbEM0TtdxbvW5TwXr7nI-Fj2lx65sOTVw0tY8u_qpciv1SwnmtxJKZHyx2VwPHjpE_MB4_AwiRyVcZsclC7bmCfSBy_ZYm_-jrMvOIoEVGF
1C3s-CsIf45QBFXx0x1U-TdZWoDby-3l6a6bxRTPkeccxLyxueVFRzUk4l9ghvw_TWsV6dP_xnBKw1dMtmlGirUgiQ_-z7DTxPBQuME_RQ_VIQvdJoVGqy5V
dWQpRq58tUi6YGS_sOuHX7hm7qKXGVFvAWlyM42-wZw5wTmlntz3oQk5Uj1Fjbu4m84U_EVD3jS3_LW0DuTFPdfWwuEZ7tl-_k3ez_K1FJ6rEO90tzMUmbuu
-05JMs-0S7Jv5wBOwoTJtWV0Wlv-Ft610E35Dz44FnPWuTj1txF-FNui04SGV72EdpYVZY1pgVym_qW-2s3GzvlJuHCd-pcVZY3PINFyk07oc-6J9lePEn0E
dpp3ZthXTpUVVAiVzJY2geZY_C7to8E1-Gl-aVcx0yDduFo1_kxp1mPW4Q3mhVw77h2mjAtpvpRY3wtp9umWGV3yJIRs-gCXF7yZ5Mu-ZVl70vjx_CdG0xX_
8D1zBkzVhbpviuMnvgHz3GyZFvc4sl8NJplTt-nw_RXR_C5V0z6b7v-Vn_p4wwj_tUqBqPWVs--v7-0D_IlJe3_kgRho8oOU_HlO6tuOWEdIZzYq-_SDF-H_
NQxQuGTS_l8dIpJkJ_G2z_WHxxx-Fl1NEc17_CYuds5Ng_fnoQAcVo6awFaJdS1g_aAdM2q_Dzu-xVT7p1uIHO50xocglxyZBBCfrCJAP7WWiXEmT4NKpHvI
TBE7w6OFCRhPGxnCmL0lcsxsa2otiz482jdJpI0DuXMofvT1J-DatUmXLMuY4w2QGVeGhvizPDND7f9riuTKrUmXHZTxY9kGFRqCEle-IJvcfJj82j6VS2Ue
bcx3XdKGR-WFu3y_
}

sprite $ing [128x124/16z] {
xPhfmeCe34K3A6vetlzfP_zMUgRNAPdz_6rha1vl5BH_Bl-JvgLEzbSndVuBBVybrIz_vvpiJsQ-_0lNdpg2wZtN_ETL1whz2Ipkp6AnfCsH-16atGMsP27a
mv7u4UJcDzYp3QL0TQQLyK4RFm8EMfsniJoxJ40eLcVYHr1z23KWQE-n10Hjv0ZI_bAj1g4uD6YPQfi_OaycaDe0ty3SVV3rphvF_fZyBEn6NMyPKZFPx-9Z
wlF_U0w-vZblmC9Ynbn3ywxUTJ2DorksoPWoiZvPc0nPHzOd2oVXx--QPdFaAlahzeKkobT37EidDhFSxEAN4PdhsoJCjfXfmaXdEHfs8z32R42Z-XmdpH2q
i1hWK9yTl99fxCAO4zLd1uinR25v0lNPmMewxMa2RL0V7TnD9f_-zEZm3NImcKovdeyx2VMjaNjw19401UgJWxfxgzI2LgWF3khk7LeB0aF8mKathsCb_Tuu
ZpTMY98kHkVjZOBclN5Xy-cfvE19sL3Pl3VOqPv23XwGZPNDUoEZ9JrN8WUNnxsX6X-JvNMaeOFpmrogR1uVCZcpiuEFShcoUIp0v83WuDHz-yqd946ottUm
xykLpUE0SK1mi7MpzMOUimlrDGUdRkPgRruFD1za8mTxAfh70YnEi8DqaeSB5E5OeeCwt88Sa1nac4jeFhA332Cq7pa76IOBpKVAGKO_bWE13ZPeFgyxUBW4
7EHr1wksOvBwviEqmWvY_iejw1BcVGO7kV_eLvFatGeEKl_L1IZQjNA83bOnKX8eH3ELJdQGxx-O0iq7dS_i8Dz_CklTUnzoaE-_fHQKzSnZ1_dvWu7qWPoM
7QngOqludREziNNd2GxMxOsYxXvdFF_PY0BtWmXRw0cwp_3r1m3YDsRzfMVltGbSV-f9C4DXws-y9Nn1VSXPTb2ty82dxw3rrtG-2ZzeWO7hpsyacDgWzVSD
1WujB63_0ToZzKTs3ntKvJlkhp-NSVjFVbAqH-s_WNlmpRlxZ_aRdJOuO7Rm-ih8_TTgp3bw__c4hWEauVllu1vHejy_I8Aj0UzVw86z3wgVZYTgXZbOE_F0
FI3i_QFJ97BK-rV9DEQOzy-ogMp-2il1MeWq7yvcG8Y3x5weWum1CGwoUv4EChFTfyMuftFv89e913feVv0vnZsTDSOzdHRZdiuLwrwyW_OYKw1xyGvEzZh7
AvkS8pZ2rGzv9hYA3QFKzIPpjdy0__CZ
}

sprite $job [128x124/16z] {
xTfNmfmm40DWkMAQv_wdJM_A6W8nLkht-XSje1tJyEVwpwKfH_mgSRSFDlzBqgjziKU8fMgaHWXbUrMJCBqjGs2o4nF6ShCHxITmYrqmEmpXLoFQJ-0tks7n
U5JOxAOjF3refP-01-qjpuxbP3rg6Z3gP9yWsoDovw3jDtKDMlqdS8izRdPzWxRVud21ssoOfVFxti_ZNBJ174xPQBlcEtyiu4GrekwWCm4S2qRa3IpMQKxC
6kB0mv_1hA7Wa2doAuvuIRxXIDRaUnpODFaP1qoJlw7DYV8DRL6Lxz0qg_8JcaoLlw35oV8DBK6Nxz1GTFaH3RiklumwzLidPcsrkVW8tLXyL9S1gmbbl32b
hJ5zfFGNNinTNtmoM-s3aacn3ufdTYHTFlmLR6esE1pEdxP5dy_0WZhVWKpg_02og_CBYAdp-TzwUJuNCClp-H-iydp-LTFdRxJuwFED5nzzlgF5Hv-VwBwB
Fd_XNtja_TqMPcVum-ivsgLwWHOVlKA7Nw_ougF7qqVFNRdogeNjza5XYtsm5cQd_9NjtzedwWuatfe_lFtkL-NJ-9Ncym2E-dp-5wi-dny9Ltt-IbVVylmA
4jJv3cpIvWTyRr7cJtYrw_9ND3XP_ewceCftQCkQ_01sti4zilLJKYJ5FfWZk_iwq2v-_gw_2xdZL93UUDJV1W_uaKLttxjjrtUFwRl7lBvxBEdVlMApldji
iyVDk4FGFMq7SLCIT4_NmOJxDdttM1tpj57VGVoafEyUA_hkiKtVFLO7T4_QGNIA0xgdws14lxNl3dE_LL3z0TS4DU0n8PURaiSVuB-t
}

sprite $limits [128x124/16z] {
xPhNWgGW54J9jAJx_r-xUPj9MhXIkEcyJUAqMjuoZFfp-O_sCRZRxAxADugvnTxaINMhxRx9AzhIJn3aFStVPE-45VOe1qIoN6y2Y4nxaW4spR6RB03c9p15
Jf3CNBijSf9YPmzQvYV0WtQSkMFPonMQ9umwmYSWs2-FvIZJY8H1o_m4EibqDdrYq598Gvz05w6HoESxnW2z4pBW60YR2ivvEeUjr0J0pQ2M1HpuhG382Np8
0Xmu_6mUusVVvfv4wKJt981lVq3RrHjvJTuPJExZnBXNA-qpVBtnuFZDdh_Czs_6c3nwFVHHKXxrEqqwhTOAlzsNIFAQWgRFqHzZy1AW-pX-F86sLNuF3Z_R
dy3XP_jbi7nQAQKn_9fGFi2FAwXI_RY2XEd75MI4GVBUbw4A2i84Lr2M3_8_HfrnItxXfZK815QGflfn0DnQlmRbm_RxaRC_yFnfn6zd-N40BDMF0n2fVhns
9VjH1Gd9lrbhCxuBCWG_k8G2Az3z1fGFsn_0uMVx2oWVjbz0-T3zUgTyEe7gz_2vIwJw4uWVszy3ODb-4838yVVhRn3lIl6FLv3m_KSLPEZ-um2wk_mQ_3dR
R-xUVl3KFv3zwB6tvVfJhp-o7nLWvlfnkjfwVmPttqkllvNbNl_W6_1umU_haxUFusFtWwNJa1_nKRsbiSbMr_dpsFDdDyTVTzz1WmnkHcljEaPtNCSOzqGw
oNqdWUo17Azy0vw42cwrUk_xTwM5JLM7M26ZqInbPm-HkDd3L6xsCDpiOGmtUnZFVUc2sRZPmnIPpgREGCxU-WogatXYzjPdqAlp56xsC4qcKTGlORZPmtXk
zZ0FRlOmXPizJEDcZvz1TH57p1u_WqvT9nF-rVCKcHvzoZr1iseQDZnEuetw0_ZFPm
}

sprite $netpol [128x124/16z] {
xPfdiYCn28H1SKQ9-zzsozwygZ7qMDhy_NUrdcarw67wS_aFnvm2_If2boVD_HBr8L_eWNuoSSXtZ9zwWYGp8_vazPb4Fu4iByYq5pv58UzKBsBWPDg2gwAm
ymIk2K1nj1JV1AJvrK7xgquGXa2iZUKexp3YfgZ3Jx1VVN4iPrb6NXoqE1aDskMSZ0NjUWgJ0MwoZGBUz_KuBUnaCqeDP3STk_FhyVI28LPwBUKijItr88k5
KPAZBt0ucY3GDLvqpa0JdFiI1nwYC8whJ_igHiBzyXyhfgJZxkshRad777I5myuzu_jR1anWsMQulfF1JIuPdcmKKKbu-OSZAwTeD3nzFDafTmqGRid7CfTH
WS5lBh-IdnETXw8ViV9NRLmfu0nJiF8xTLege0MWvfCDmrh1-YW3pMVeylC1ZXijgAD_VhokATzeGUYV7r-Pwe1Ra0ExJdpfQWSRC67H4vLhrT0MLB5nENra
o8ESdZZpsprPot_Ip6nQHcU9PasV2EWZivor-V1j_O8bq8c6ZwP_O2r8gHEk7x4M17IgN1uuHTz32U01-rTvu1Lz1xMWhAGVeX_IaPDpq3EuhzBdSyYJ0RKW
MVJzPp4o3CN2zOkOCRryggRlmuEB7gAt8Es3NT6_Y9nM6_OAaYjK_Rc8FTA3sEsl89Oh7A1VvC5f7G9DBvy4w8ylYScUzQSWMzwC1T3_VArS_RoKxyOMD6pN
v6nFv4blJ_pt-fc8nvVIHMCBiZRAzh8-dqJBDtTNNZ4r7pq1cdQ9ljNK2i2cq7JJ0QxS-QdyttwocLfG1oQ5TYd_4Ew8_Z6Ltn81xKhUe_h3DYbKcWymotCL
L5-CEuSu7M2MfoguFjlMZ8Ed0qpouMBN6OTUsG3_mwmzvEVl981ZA4_Tnpg6HFeUlduiT3s0njlhot3zMAZwpGxoxW7Y7NqcO6uwb-jdREzK5kjNTF7KtKhz
WM-Uv5oeptTs9oEkqB-U7dLwMgAVpK4nKoBJz_XZOFeLMpzCj3C5nqJCFkQd0AJVbUqd2ApFoFvhlRwdAyg6rNv3VWxKr_-s0SfH5WpTriNclJKU7ENydZBG
VsWcsOf7reVhIQJJPHk5BCWkEfbmiWac6r6s0EpGztfFfyboJaBOvxrVv442YPkyzsiy60cdhVKUpf15D49Oxq6wILphFPnZhVTmsbhluOoztjllGNgJiD5x
-pqOw7sgtEQW5TJjrj_o9XYUbk7J0H8T_G7yvmC
}

sprite $ns [128x124/16z] {
xPfdejim38FbMBAsSF_Rjczl9EmJvAxlPnOoG48CxVvS_hE5U7Xt5hxZddOvHNtWcUxTOiB06yRITt3W8oESgNxFuHOGGOZgWii09ohL2suWRqx2fOAWVWUN
1WDbSalQ6uoqVNQZFUiT-04JSzjom7SOGTJgxEz0hpwvBKTC8meQhOqeQBGsycPej1BAJUzWQv1H3FMkuU8u7c8sHu6Qhgzv3asb0OBUWniMGFHtCFGEJ5Y0
fp-_daIhJy_ukl5Z2VRp1leT0nZzZXjlCFVWnfjM18AxuzORcl4yXCdw2P_IZDqdnsFtFyb0ydS0mr-zuV9rDpTcdtUk_rAVZROEbAVgD-ypFYUuJm7JrqVG
9jVd1jZdwlUS6uaWG_YCtZ75Vpo2cCXa_KJjfzSV97nqzSyDUCZrUGJLoVgZrcuPoS7rvz9ezz7hmp9ufH06pDHjIuP3S8Qw_dW4OQr-CUZd6CTiVR3mqTS_
i971LtB-u6DmD-WhfY2irXyaV1Jd3sx00uJUseJwen5KeQv_7a5OhzzO-EZh7-3XezVVIFW8pXyiWeP1Np45uGnzaF0Hd3-80IBKzSSZgClrUGI1KrAIw0yI
FdFhdnlGI_JhlcVSPC33eAzOnlYpz3UIFkhpnnsa_Ku-V_06xFNrpmEmwlNvIdYih__Afc-z_Z3DNn4e_euE-3kktt3KsWrRg4ZrmrDQTC3TyNn3Uxp1VtA3
QGjPy1Lvlduq_VyuFjsquEeDrxr7F2Yaq-sddetjlyxSW1TGz9S3zSNxz_KUx8wowxt7EVJUunIzzpXTxpsEtdkSYzvxdA2_zegJzTxZD4mdEmjYxwtte3CI
XDvRxy7Wx3IzzpX3isrSxq57O0IzzpX9xprEqtkFCxJUqtlGVHClz9xUWzvzdogurDD4bLjVCXECtKrZFvAHS75_0F_v0G
}

sprite $pod [128x124/16z] {
xTfNbgjC30HWgNFM_bVxXvicuHe42D_qdJElBjjKgpqqzElwYsDEWPubJFbYkAUaB_bX1hfPNFB62dIZ91-j-AJq5ubka0N8P8kh0DRlW9liK9bCk2w0zJjm
GnIQeqlv8Kh3Npred_KEmXALQyTob3DMD1Xrrky0f-ibWq6hamq6hKus6BGwbHM3raHZse67c6cAzMx34HR461CargRzciSy0Ki0-mwot03aUq7i6rZa1W5U
Vdi5hZvxYnvnSeihVs_qSU4C7g8oQwJ_XBek-Zqa2YDx-i5dpLiVPwVFQd7ZLb1RijEflMyKJm_uCivCeBhZWoScY6EJJyL3bt-MG83YQsZwozyJau9BNLq0
hsWS0Dg82r0KAmvoUHpPWkQ-YGFidaP5Mx_mqgcUtUTNVHQVbLkG4y2_VVKQm0V_rjMiB622-LiXMnzy_NXhMRa5zJtvBwlxPI24ChT6OrPkGOeVpPpQZtNP
7qs8hDk26EUZdcyN8WkYt7myMETZUq5atHPKTValfIcqBUks8BatlzsUZmlWpVDn0VAn_07oLQyuxyulyFBRvo-m-QZoAyX7yEPZd-_WvcEVd-3bjyyVz8BD
yt41Wda-da3LF1zlGSiy7sz1OfsF2-3Dyt41ida-Vj7vdFm2Bxzz_jf_swqxa7_un5XptwMo9f-RxC2gstvbTpuNsSNfpbnMelVcLdwIdLXxrt-4p_FZbBtW
-CL5VCble7POWziVBk9slcl73YAwQ9G7-LmE7malqLXfAp-9IZzpy3J3Ipwe7R1EdZnrzpe_357YqoUFZR_dktR1AMGJjV8bd-irZoDCKLjV_lIwzU4dDk7f
fpqsUTv6tprj1-qV1vfYhX70DtVl_WuoOSc-UrYpxnusxRk7sNSFS_RTmwBzirTOjUyUDkHobJICktT_1qaf6dRl_Wv6qXlstSEMN6GGOjz1EYZQTmyhzjt3
Xdtti6NRFViEqad1i7ls7GnqNZTur5EbcrVVv7-2vUaoFXMbwEWNyDU_
}

sprite $psp [128x124/16z] {
xTbdOgGm30LWoRth_gVTacfYOAJ1UEltTyiRu5aY4_Xp_OVMEmE_YgdqegXVajxeGpMmc6sqqGmiv6ZKxEBqaOC5F9tmS2-Cz82_CpqHGqIuXSeqMFS9L261
f60gNKYewDc3zbTz0jD8PEvOjiGtVoWwkghPPUcJnxAdQVpaGIldfODskeYoGJjVGc30GhT9dFD-AmNd3B6q51iz1U4KCTHWNchYCidLYsS-k_uAZFmsQ3ZH
w4oD1WRAvsaTH3gMlO83Q2Mt0Oxfmmkty83svNe30-qeNWCBsaGCHl3uMx8WeaEX1mB_z5M7_6GVKyufF3oL3Oue6fMW6U4s4P_qVQCbYt36rJapU7XquUDS
bUFJf-kizw6zMQK-pbMBzdnabXXYOfp2mfu-kZzN_H0QtrIYuNU1lVlqpg2lqOup9o5qL7fg0iMJ_Es-omxxcTkqx2t2SdUlPasuWZ3GJRo2aBShTQYqqH1s
A741D7jNAr-9AEYyFSxQXU3Ky0Yu1GYC_Aug1SpcDDlwvSVUA5n1LP2VVkRd_dqg3Gi6XIk8XFcgxtBU-U-3Q0KfONuDNPN2tW7JeW8wQVxBxCd3hUuUIfEi
e2pDxzhdzmiM9Ik8XFbzKAON9OJQDy0BLX0-bw-w6_qIchi9vmG5C5VokrAhxlgiO0B5o_aPNWpvl1L4b_CJl6Yi_BGcdrq0VJq_gnT3Fgi0_bf-ZvUlOQEk
pW-mGQlp6_JKydo2dXFcP_gfE0qlr5S8BxHdhg0iozVyxpGZQmMHBB-num4IOmMXxAk2yB7Z6P1H04C70llovJS06G-9cZjw-kRgz_YMzxLRjVi_N6bWSezN
49tA2ZRSd7mQbi-XX7Vae-0tBU66V7ssVCOYpieVhubOgfsStxhbmvBrr7pgfWzJKZFpiViBN75YlXgkdw7vsTUF93Jv-KDRcZyEOBCsVro0UNt-Te6tzVaP
EhWyly66NfsFiENNve__EgtCzp2gw_8pxC1b-HLswLNvA6dA_7mD0ra7hxt_EpXMYSq2KpZOEXSx686fSBedxs13OD6yxiaxc843gx2rYRYoObnzFUdUvGxc
u4-5CdIFWUvIWKNHJH1uBDr20LUa6pZWApHT18a5tLlRGH2o2xgtheCMvChQxeqQJL9WiBI3y2IxjdkZiBPxexAsUwCsjtlhEmWNcOdTMzz10zTbUbg06VBQ
weySFQDfc4Qx86GL_07--mu
}

sprite $pv [128x124/16z] {
xTfNSkGy30HWW3dZ_gVzWxED4eiQchtnUzq0sUf1ZmBzklvY7uEZ7yLrUTBC3va-v4rt1EQ7V38S0GNHXWTFrm81H9c8T1PdKN17m4KMPAOZJ1K5TmIcoGt5
qBUoJMvgzhiNBVO8zAAzhplQvcN3zb8Cicjuy7GjR2xQVN5pqUwBcujsN-QzHRklC2tW9iUKpS_xFaDpJWvZcfBJEk0pFsLfOeY2p20B05spea0Jc0J0GK-_
bkYI80owOWHYyVi6VWStWGXqGJ0QTljeIzs7tq1PGFp2wSTN40lCLlcCLakEmNlddFsFSzxxa7AfVIC0A-NJSd26PjZwcFjZ5THbOkHWQ9aDvNu5oQMUBDtc
yf0huqxvD4yF2bqkt2WVJnlIUWNLzV7x1n2MJxyvSlkaBM-VIZluAW7hvTEFt43XrVAf8ZqmFO3J4AchgPOBvAg8j6Ze5fkwY1HZLojeyaarJvjarEGDBJ0X
j-UjnPDIMIqVUc9ZaoUzvkYTPLACTJxcDkH93MR-__BYXU_ddsl8cz5xQwtMrdhlGvwftvDTl0nUtfJ6XPHhwqC-6RsLd7GzsiKAaYiqmSp6CFCZLxHZySg7
zjYr_pZWvnjLFh3vke84Fx-fyi7E5rK-uFcioWSqNrVGWCxN5II0-PhwI-3vhCe7Ez-gyi7EJ-hqd_p-hGrLFaUlFpIrVOvUVsayAR_zwyyqHEQC-lbFNdzh
hDhdvFq7JQtVvVilwTFz5_Tw_sN87KNL7nQhhpzG4VhWONvXpO8sr9x6OlNa4Kelj8BDdjQXsTDOKFh5riPcJmlOx6a5_lWBdy524mpE7Zw3J7C1cpsjOBEd
TMpsD6psD8FDdkQnp_srZCeUy4s4J7S0ieVD8Dta0Td3PT3JVGsRFMsSUU45dq5waCTcJqlOx6aDcprj7CWUD8EqoHt87Yw3ZlRLlLSzzrL0z0zS4mnBtyQ6
T9Ctz0luwry
}

sprite $pvc [128x124/16z] {
xThNcjqw20LWr1lIUl-dJKyy--nZuuQc_hSf-8jMmC93xzSN4rBqz5fynoziNwNwm3_TqsHXuC7mD574in5UgVeYqWG96nBfCWM2f5czOeTYI8Lj46W-WMKS
K2tToZ4EOdTtetsj9_03XzpRbWEk646XrKrxWeXRH8L6UqnIQBIQJs0gRbVCWKQheXhQmJ3KL185g9BcWeSouGoWhGl_vzKvsZ0WqCsWmGIqpa6WdC2C2Rnm
_DeohS8CWzPOJ26_RxnI3sPC4ONZryP2zr4dpBxNwa05EutEjUISKee_f0Q06_U1dSB9un-jfFeSeFJlhpGkfCAGr1F7tt8mVmyfFNTjHo_O83p3mU4pYd_e
KUMvlgK73K0RGW1s3f_c_tjA75EfhJNc_WCF03Md69nvEKY80XyPGNsb_790FXKMGjPRYOxCtqDsl7y4RRPB4sl7RcC9QHP6a3ny2fdCE8pZnYlbpk7JCW1K
d9JDSgxY26fu5iXLNE5NJY3kEtvtTIYMbNzOtjTztCMRU5exMCZ3Pxahc3nmmaXBiEGEL3RlAZvt7CB9FGHR747YNSduWNrwyaPwgwkxwpVtuhSq5r9ftFz_
ABSImyFV7PRy2G5mg_K1ZlRlRracZx7EkGeWUkUSVTdvE_tYqW1QQttF24eRzG7qx4qK9k_o3ajaGXc7hi5zg_uYYlKh01uGvJt3nnjZy6XmpIbwPuqXAdzx
XB7EnvGhZtEt8AkuxOYG0nYLwqiZgCsl7-NZHwkrQjLdOVWi-TUf3rfuvVfI1ohQzOKHDBJh2oC8klMb03Zb-b80acvzSGHrtVhY2DgygCVBxz_I2BBR5tLR
hwsQEjR8UnT__fi8fzyPI-8U9aghaWeWrOxTUWtcznzhILu4Uk5BlWNGZzo_zsxJpQwzMwkFAm_hGwm0cF_i7vXRgna06-cbxj61jRT_VbtrJyK6lH3gsBk6
yf2rx8tyulkR3PaXCqTVVqOhwVUIfppNRm3Sid-JfTCV7aOV04fAyPUKSYvru9WsSVKhhu0S9ZF2byVfNo4h9ah2_b5P4_RFh_CDshrEzXPnSlPU9uEHrlNN
_VvEvdMojt1JipS_WuuaLJTxigwRFPbkzcHMDtkoeFlTNrPqioTZtAxG4ShPcvz1EYWePcz-1WCTnxhPamsT7tYPdq4wAUXcJvPrioTZtUp9Xcxsz3D85td5
xEbdqDDr3QTbkaDJZxxAdM0ukesB-Q1WwHtuyXq
}

sprite $quota [128x124/16z] {
xPhdWeKg38GJEYBa_P_srhsBMuY3kCVRlh-dK3BCW4Z_NFw7VGoEdi9L-OFTFD9watUgenVZctoWlRG7GRxI_4EjTmAzW2WAaNuMpj9vUGzu4u3Cz2EO8fsN
zy3iCi5cw5RiBfFizcwZVQe7hiaKzzgobnMQly7g7kj1a5i8YqQxJbmqsdNYJKQxNQv9vcMZhP69ThdA1lM01msqP9ONv7PvlPU-Z9eiO4Z73MQUEabMO5AH
0VOW3v5ylG_rsfhFr754crn6IIMbjesEc1_I8CiGHtT9WCPOiDjtAX0SLxejbzny-Lka8rLMIFEhJufTs99eKePblNS3t6MDY_kD6baHwO87umDBJ9-yfzsv
7qBSmze_szsyONg3RIY2iolk0r4SqnSur4K1kDKDBSSb1yet76ey8WX_jVpDBXrOz0ZYMU4QzvOQF3kFW_3HgKmTzqSZxwxLiftu9s4bV80TY2t7SPXlplpx
XGYge6R2ft7OxywxUJw2i5sJ_pAFJZhLGBFPbF1Hc-TTjFQFsewJ0Wn0y_ux7ON1bzDS11MbzgEYLiViX-hAKn44gCLDski-4K6CVDSZoMkGCKs43tzpFYbs
M5_CY1WE7_-DIPM-O7HhsU08EZcl-NpS8gUXOijVQdwR1ZY2z6gQzryS_CEFdMKNEKb3C7nA7tLv6tEVvJPwq5Fx21icWAWEFxprXSk7RgN1Qgs7dthi65pL
jJVela5E-bW4gRrCWscc7KZPk7AW7tQk0dkjfXeR4Zvft8e5daKPhRG621ypRYG3suoiZIq0vTScKAaRzFlzF7oALkG0AD1gWpiF7wyriGD7vgGLbq_3nm3E
3Ao0e8rEaR5YCgW2DM_VCFavVN2w0Xbo0Ajz8OcUuRvU5I2VX4_L9xXd_Pa5dqLGLTfNBaHAbuzYBq042U0GMXFfnDv5Zo03j4_Q_8MJU1DTW6wr_NYnVTPF
NlN48PEMNWplBSdfysEjyx7D_hwutx3G-5bjtykGQizEPKRzVzL-eOWjAUs8_-e6xFI4MK2TGJxR_lZ5-puzeY9rcZ91QVMkItVljJtMvVrNGyvVZ0f0tRz1
1_0uBb5Sc_uTkuNSq1C4pjXz8lZyqGow1k67xbxGvy_RoWGCbrR5Rp_v-X9qof_2zr_vMCCC5IANOtfNHNk81hcFmYDtRus9Ol-XctiTg8waaaK6OJTu9Ej7
rTz8WOUpjHiboxzqr-NkAehs40qsjOFwtnjKUvsWBzOsTRbO5UtX6Wn0yvq2_9LAdJwe27e3iH72e6XOyxqLDw4zI3LLGBR1IkNhxrnoRnxhWCFk_U6RO5Tb
WisllGQvo-raca7kfj8KHcxcfU_zGjh3DRYEftdsXxItzAAbdaaFQP0kuf_HNYVTghrdD9XfXNQRzXxI82tYRjBUCnfqj4vPUzLpdVA8z9VVjssMRiE6D8at
z0_WVtu5
}

sprite $rb [128x124/16z] {
xPg9SgOW48G7y1QOzt_RBNAPE8kDqSxzxKrPVrC_pVGWAz-NFrm_3fry5btI1wB_5FMiBwHEFfW-wnloXyvWK4lkFrZTCiW7CEe1et1nim96flgY3SnEAFXL
0SmP-AWdMBpSIeXwaXZkBhJC6U12sywzPRdNA-IUKEe8Co2eNoxBezx6I2Yqp1cuHMzdTYSABOMbQGOkAes5lDyn7XKx9GFMGDaaiEVf13bWtrNdXzyBsv-d
1zezwCoJutFvLCqYhmVoqy001oJgQwHEqDTqD-dxkTM1qru_pAfJLr3DNQ5fO7uQqAwGTVUnLVB-mQJtCttixilBajuEI0sl11QpgrlxZHGZHTzBXQXc_Hdw
0rX-jdu4rOUZZmtG4VGt_-CAD0Fzs-ZRTlyoJH_P1Zcbi8OmwmuGFepwWmqmcKBTzvcWNukWfCpzXoD8gVemWdoBVfwdeT_8PIps6yEq6FzvFsc30GUiFmUx
P7OtTUkxZW4hqb-zI4qVlw-14QI0MGJfRwoc_g88SdZ6M7zZFl1V0OIFwJ_cb-U6SUFHV-F64EI9UAplx8IFrZyslvN8uzEZUQSF8aWFzJifXAmD92-5yL1_
EQM_dWg8xAIGhNxT0E5Glzy-4B5DTxB-hnjWFDHt9y_67VwwGZLyRFyHzuzq_sFOh-wPKn3-FXtg7_m-NxBfFweHv77f2r1__q0yyf-2yDdw3vA-huMFzTzo
vVil-h2WQqt_gl_g-j643s7_RVs7nOGFfVxKSIPy2FKNdeB0ezVpnzPV6q5QXPM_1NJooIan-WzhW56hwq_elsm49Q1_llzSj45_CilFwB_h-jaKJiBvO_E_
nLOVVFuQqVahQpFk-9fnAGPdukbtBlN-e-2OBrwm_zIKN-Rx3yjYue_r_W45u4hMXrV2cQLVxpzMSFhUz2danlCN2yUyUSJrDnn55d__Zs99bVw3eB-2zy_a
_PV0xITRtu7xBx9-a1gBqRzm-_eqCExzFqYTz5RVvzhjipRVFW-rr84UN8pS5NthFUp1N3PXGLLJuJq3m7l6WrI281ObCWWcCNkn5fH5aYOyDtCnFQlTRsNc
UWyJzNPcEGFPUn_lGJb9J_JUntkmb_D4hlSmMMyY2e3iGNadFTTxc8dhFKpaUW-JkTxZUr0kqX6zn_TW9zTP2V_LynGhtVgKCq4ESXjXc4xIU_a6_F4F
}

sprite $role [128x124/16z] {
xPg7SgGw44KbbEFz_xzzHTMZTcXsk987RJuRZSEHXqjtOw5-N_wXNV3sfzbj0tRgzbFi7JXezaVRNSU9_aDNu76bknzkb_WVOG-u8IoMwmH2M6dF623fDVQj
WB1o1Ll517bxrcug9gdcwKBxirPWEwPujYmx3BEWA7fyIdUBxHo_eD3E4HOKsfKhq1cFa_H4eLr27bg1hbX6NdozSpQYjrWCEGTOJIFN_7BCdLzErHq0-ixB
lxC7nZEeBnyPZl89TALU3_J_3tXwG5MySkCtUCK-vD_IQ0AZz9i4HBi3TBipT23zVm1sfqDysRTq-O4DpnEVlFgQPwsYvzpE1zxgDqnIxFvPaTNSW1EZyqQh
TN38zftunsfmnVZvx_6KOrkfdyz36FPNhoGcZ_ehgJxKN-ptFp_s8Jz8xoF-TDD3VRl9Fwj0YVlbQRzY2oXkxEhFCU9CTOfZyjV680r2DahYOavXkmr2CIPX
901cUjNXxPsck-IF1o1249thmlzkKFNKprjGmtt-f7_NznHYav7Y_aZZn_q1GFecqpF-JfiFz-_wby8Ht_dBjaL8MFFXVlVwFHSvrxhvsu0ovuz0EQrT4pzh
GI08VmRIgN9lmY_gBsj1-bE_cSWVG9gFc3-atnXJW1eE4W1dZ1xtwvlcmyy_wolSxyZfN-tFFzaFeJTh_4V-QG32qtw68Stdc3-8l-O-vYSj29no_UYs7NrR
-BsOFwxqwJkVAlr7pSjNVw3vmxNvaFcZI_-n8dVr9-xVHFEX-OFq7sV4NlrL-5aB0l6BgUdyYiIh7znVHVFX_d3vykd8Zl1l4FC72O0TyfUB7zMxYAlVJ_ua
C0tvCLn_2WYY1NKCuGRzcjp_ZTPJIHdqUz3yxR0xdzxamhSnVnlpQrcjwFrl6l9RZFcDQ3xS3ptYhymlMn2ONxu0_ljielSHVvVLWljX5AK19FyYW7R2Nwa-
OXXzNwro21sIIFHcVZF6OWPxgzST0Zb_NBz__SWMaim-pnz8-Jtc3q6_MK06zryBi2Nv4pJDz9FrJnNY7tm52aRzSakuJ_dHBNj2XSyVvHHRvkUNeUkOeK_U
VqcQ_Mp7N7-yyrZCDtk4WDLVmxFBALRjNEeBprzWVUEOFmWz-zY0MNyXFtycvvz0_OsqZjL-JVQ_5liDATyd_vTtNuy3GURVZyukLctztUupXdUV_RkkGpEO
XUuHVviPNphGsmw0jlEL0oHx0e-b6CN8M8XNdBRs-IFEscTlEDlQPuyuRkspLvoqDdkSYiT9QePrsVj96LIJk4NP-paPT6gUkZPxd8w7g4IqEeFgYxYrsUF4
jTdZrBNPu_IrsLkVGVKXTc7srcVGgiyf2nxrdA8iZ_wIUu9kr6CO7oTnc_eD-CT_
}

sprite $rs [128x124/16z] {
xTddVkGW30Hm0GPNfFT_slJcAhJsu2lvVxrBPlDZLdAXlzSl5zlKq5sQB6ycVqiwovVSK6MHPOORgYZ96iVAwMk9AcZbG4jOhXT5YqmVf43l2CAFea1-0Z-9
mU3fKc4IeobSFMZl-WGDYycrOpdA6Hm1eyw48pXTbm23rgO535gR5Z1eRNfd6BGGWwC2RXAOWLHHeBmsx0HCEGD1oyft7YxG0HO5jeDEAg1zGHJW1dPIGNFs
-3b_aWzvXkV_JnOwscLTfyFcTyhBkqZlHfbXskEbG2PhVYWjO8BcwpDuAittyTqaRpZEjFAkYoysyfDo_7f-ac8R-PCoVT3vekm-JBu-WNefadFcS_aHkdlr
_E6HuzySRhkJy31VxCkdNNxAj7bsl1mDmbkdvSpBXwpvtho2iknZSxwJ5MK5YPBlugiax_euCygx-4RBP-loOTkLkLVoXTOID5zVGICqNrz1WiaVXs6KbSaw
VL9AlHHBtptT6In5ooSRoSfklYjPFcJL5-V7akCdi-ByuUPyeRa0pTSBqDRE3pIJeVdw2f9BysC8ZPBFol8vbU-9d98lolA1vtjb-Q3patBywFn9MJxeV56M
pybyIYbzN92rwdEO7f2_FjNz5SHtv0zA_T3vGfy28D_bd4iVnBM8VCEJs7nFVgSSFpgVwPs7vki5R2xCNzzqwmLCr-Md5uEKyWL_lrsoFWbtT-KhunUTFv1I
G3BBBzZ-8cAyAl_HLy9SFtzKxhx1-Goz_xA_XMhhvWTQ6chcjxIMw-MFjC5Loy-5RpyxCkfCtTCd9sSJDdPFwI18edtvtlVlv0Gjqw4WO4xTtb21D0EsUxgC
xPuEspsTntPF5mN2KwaUsptT99VhoGBSlVeT9AC8x5xz3aQocx3Tqx5SP285k8Fqe8Zjdgx3TaytORkdOspty1saanfWz_0TREYyKHxMqHL6UFKXzmGSw38X
TKRHqr_WrpC
}

sprite $sa [128x124/16z] {
xPhPshKg38FBB0Za_gzsppFRjH8_-UVts8SWZKLQxElb1owL7Erp4GT-e_lFeZxn5oFQ9oPD_8iPxHEIiJBJ9rPVoVO9A7X1iRsuYZUKdUeD1DNP5lm9Wbqp
y1q2pTkZX0wH7fvEj9zh1d52ujcqd42p8IbcIEWpqDLryeP4gr4s95gDiY7HQbGd9DejD6S4hcCRJVZUz-3jDH6RSVOIQBGG6YG6ySrhblOL2i5UC44pilr5
dizuq86bf__OTe35hWbqs6qXd1ztu74xamb6Y4JugR2lk4ACSDWbJDWNL2DCkyBV2FiD8wZ_6_e6Lk_buAw5_QuHBeUImdxV25tCFgUtMyIk6I3A7wnFfIHd
LnGj0rLAVrtX7aNzYsX2qp_n5rNJRnVXb_Jx-n6Bb062fD-8_-iYRK67eX-O8OlqHaDvkk4_54N_aB9FP1xkYlwKDfz8FQpemrQoeXyuVMKBEZ-bVYOYgiL_
IFfT-VMDp5PT9Nqe1w_8k2Le-exOV9HiqKpJJtpu4T__AmudwZTHVoNCHLxGXt3oYU-AD8UPhE_uHwDTu4lhlMLdglxgrq7eonJ-50GGNbKvw5EG9-gNEXMi
0VEzsg7p8NYxfE45djfyhlykmt5E_COyYvVEK-kguXMdBVZwt_xduSJZVAVhBeFhnZIl7UVvgfzRyWxnJIcZLg5Y4YOk6LuevYMwxdBG9QhfM5C3RGaKOHKt
wKUDBiG5lcHM-MPBf4Sj_A00lLQLhiGEUj0Wb3SdNOZZo_QHBsyci8KuZxSSklw9j_23GjRte1_DU4zHzHlUu_dtdwA-1u4Jglw7vlyJ15BNmtFZLhwDrQIc
rwdaty4klx1QcTz_gjeIdlny4ruGrFKqmOBzxUSQrnYH9Q0W62Q_bhSk15_hF9PNgNs69VCeNSZ6Uz3ym49tGW-jsCe0GRhQt8i9ykVzvcV-tpj9tI_pqdlG
0Gp7slGTaGWYqG7DOWCvTG0uetX7BTY2DFtnzm3-A4wzEf7jcW6A-e4xCyqUQC2FHCHEy9xcmRNfb2T8t6DtlaPnIxDJzjvA0y-PdI_zuQje0zjene1T3AFm
s8GpZeGjU6Efs40sdex7gQQmptkVoOCcaZPvx_DuC9bEt-0zYOc7w2QmmODsaxJ1UnB71kz9z0tUavXxlRVVW_P1uaRlxVTWj8zpuZQ7FS6vmVeI6NUOmHuZ
v4CaUViA-C7F
}

sprite $sc [128x124/16z] {
x9bPrk8w38GbptFjVxUN3eJxE-teE81x_fvzA8ygfQ3Vbt-mzSxGpy9KR1JrKzGRdbH3FnZRqD5-w0mSlgVPdwc-uUW7u27WQIqS8R1w1fmmGMHQWieGM3q3
LN21fEYZw8AB5FtfGlkpPc0QBl7Picpn3iqkA7KBPh10_UsoxF4n_892kt86dF1n8byej4j8J1DmmJBIp7jVYY8PWyKmYM0rTVsRbz4aq22m_WuovcYjbdm3
G4xvHYcrDSmXw6i8r1nz0HntsyNqH07DMETZhY_Um80XEJfD6n7uwcVrg5_e0HkNCSPSFFxOJz0HiLBQ66jj0vpzXZ5QiG5oVvTp6FnYkF3wIdgkYRNriG0o
9QVWZ6OYIjjUsOe3ZSvGE9290R0P2ikK-BWSNASle1kyrO0tIFRmgt8DBgEHDZMyI8jcv2YEJZXp2-rYlIgTWrKdZbPe30jkvO5WN8Yvr2Qerf9Yg80M7LNs
lbw_14FxPNx23J0t7c_F0ran4nsA1DkOHlfCG-98lsrtsH_M1A2VUEgBX5V6fmeWZ_Gj3S5OVwUL5BmrMl5HNpyA3ojjd0y5EmTzsO9Oq1zGRkIDKW7qusHz
2EOZwr-djLaB2alqvosepkYtMdACmNkt6S_-1fpp8SIKIuM0R46Gz6iApYYc2JQZobKw_oQRJtzwDLf5Bw1TR2VwcFxOhOxxMMfZxtkTyZSURo2b689trkZ3
SDlfInQKnK_dVKyxX4RDgi72H0iIxebogRxWlQelgx85CI3twXo0aaJx0LhDANghCs34JwgX-SZ75FPjOrPQcmQuE_Q61pBtOyMLyS1y97qc2gqpZZQoW1tZ
BG_q1GkQ-bhbRz2TKciNZ-Rm631ricbM_tqO8sJpMQ_FrE5_jBwcZhfSNxOW_6Zz9fhFUdq8vhD2N_xjl5nVjY2irfSjY5VgAuoPIFtSohzBMJIVZQRfRJHE
i3EnMz9lgkUP80u2DLgcbs0vEi1Sx8P85v3pfnuUc8-SF_cKuzRc6gM-E3qpgxqntjhWhGlENVuqG4lcq-TFwRNyYVRyIROWQORny_dJJXCAnABygKUgFdt-
5Cfx-TCO7XKeEN_QFm2azb_8dtgKiFwf_CbypPz8o9_6iE0-NVwKvFn9VnSy1p5_sXcMNpb_SaREdwoOF_KamVxcygUIRvIP_4asm3odl-uluVRZzRFG8wt8
t-G8I2_G5y-VP_vvRBLYZRwc8mb36juYZVMzb3_s0rt-lFzb6i2dlSyh_e_aD9tuVvtkL8kvc3-LU_wqsyMu_-4BdNhnUh-XpsFRygSA_1y_6GSKffrzh0bD
kdkpTp07T--4dFZVQx-I4ilrZvgAKng0jDdFI9-1kXkG79Gc4c1CqMejcozlv1lrltRjuuf18821gCWP-k_MHrs1bTyuy6iOuYgpVr03xp_KK-iBDrWWCKNR
cEs7CTiRgvdsh6EsLpOnxTbwn4swudtjGGtAW0RT7jDWf-jMgBty66-L4GtgfevfpqQcFLkPzcoFjGSrg49jg3scmLRb2hv_HoKiGFg1RuAzKKpJZnTrjRx0
umK
}

sprite $secret [128x124/16z] {
xTc7TlCW30LWWHc6WExxF-q_k-Na84FK-NKlN-TObg2Xp-k7Ypa5UY-Xuv_ctoMTyQG7CXOPht0WGmaIH-DqAP61Z1iotPSh4EpEm5KCA8xkmbyWs9s1Rr2e
dfRQ6fJQjhhHljSP18RAshOSCM6wAIRCucYMlhWjPooJfngj_HcuYkMAcskqywgZ0QxXRkha_JxFqsq1T-Re9jnRdxldvsrq0qEmh4470tJT1i6q0dSO2AQN
NzhfAbXWkiR3X7AzqUgZXlykTL3NzU268r4qPq-3Tjrw23RvZOuvetpGiM2Lx-XGKUR7qXZWLgFJvKSw12Zg_yBuYny-D4NzeouPFbp-FsuNIeVEWk7JuyJ-
sCqE7taFHvuTGHt3U9jRD-zpmuUTedqUuQdXmvuU-9XpzFJ0zPa2JEghbnxoEAihs9DmKIuWVPVrK2QsvCfpzun7ZO7ms494_pdKpdUV9fPgdjBZMLN4iLlw
_COhYoDxeltXgaIKiNmdXezk_yAlyud_7z6XZUN7qvT_pt-KjzzfgFal8EUSHBvGHVv2NUHBfuPFJYC0KV-IExFnTJJYp3Quc-RB4GJhV1R3npOVOlWOvtin
VCpovGY2VNwJmqUVxrFs9_CXXey-Fnykvbxrdw63bNFvyNWnyRh_ZemWLkJB1MTNviiH14s-E6q-bm_zpiSTBXcRBbyUBMlovT0CkdmvWheYNxRDfAn_EO9m
DfzSYExqIfh5yB7eVx80Wsc-F5nwhtp_CHw_U-VhJ_m--LMCFzjyDxRyQVK1KFOHW_qdqzW0ZDesETP_Bw_ws4X-U3nSZhU5WNm-62L6__yzNahPvc_qLhNC
poHrmEBvbuVQanoiT9DdF_LjBC74HjTK64XqNJTz_brojhKdRRQr9oNRsfEgRUr9tRRs9DlQaxnjxKaHT-5fLB6jFQbXkK8Q1hLdMuEa50rgpwu68-arszgJ
68iq4anha4wAjhKdxRQr9pNRsfDuRUtPro1D2Wjhpxu60ysxuBITLhXObFxwFG5ljCoMTgNewHFuyHi
}

sprite $sts [128x124/16z] {
xPg7TeGu34LnxzB__-qksQCpun0ZDC5usprzsYNuHO-s_OFv7nkyKwlakk0NO9VOAxvmJziDsGd_fDqsF18UimF-J7h2xl24f2RRFJ9aFT4Uy095hx8JrTml
Lma5D7kpFQCGiFSEMZdW9emw6Vu6UyFV4EuOTQksm0dizmz5XyIABV1uArdF6NKyyh6i8awXwalwXDDechLhd8fdz0edmmpbYhDHY_O-4PZiJUVCZm-W5llj
M6_m0TAlnsuZg1-XTVIV4mIW2RVV_xoaq7ymNlQByiFx1pzhHdhzZ3ymdS_xbViB6XVUTL3ZkZzHHtyR-SjLlv7zjrqD83xarqptJV7p7MZn6W3uEt-PMZwy
7pzP_X-7st0ImgbVYVtb-upCMuVx7Yt_ja5i1V7bOwJ-3GGLn9UF5lZvBW5n-UZTiKFdXDLrKCS4jwEvdnF7JuiEZJtdDqpvJF1p5UIc-laAAdFyDUUCHwJJ
9teVy3A9Sahpvu2-KZxGPC1u_h8LP0VV5U4k-pDRFkGNKGT-FW3mi5yTuyVxjN4-n1XJZ24ugzL5F__RXlkC2RdX0QZ9gO_yaIcVpkyAdj2YOVny1TKJVq2M
QhgVYSOOEFSZj_par_2ov1YSjMR7MXzI0IGY-VlvD_ORldpiIm_9wS4Ts89VfB6Vho0tzEUlQM6s4rG06ga2VztUo4C_d9mmzj_tCZ_ovKFVpUhAXV8WzElJ
ykc_c-rOhiEkElYTzstFfNEElH9eJ_n4ZSuSr3Pam9s3dpcaw2ieidwYrPpJJYwLpBoV2m2S-bi2RloaJ_oAYH_vwxRPr7142NgpHtzfxUg5ECFvTvJrgJJe
ro8wJG4wvfyZaZzSyHDAQMrqNxsy_xI2AkTdOFni076HNzFqkSy_FkaUJo1zdzzwoNc2l_tltz7YUp6h_DH0wTpVUB_xo7zMV-HlLsvT1jgRUN0MnXIW7_df
hUhLK6xJbn6ajyygV_pplZYGWzMzMHaVoGXQw0VkuWyLX8U-W4l9kPIk2cY997vr_VmhSCCa6sQIy-TsvlGp9XOSq1BbIEAF_Cq7yXFQXLmQlAz4z5R9RzyE
HafY_2-KwgnoFp1VlkNyNtuBbDbBF4wMFVuIP1C1Wkmnsp-HilR-Eon__k4Kd8nP-_nB8C-Q39R5pny9XjY2x16mA7k4dfozDHdCstNYgkmHTLNs25YKFKBD
VUwFnwxA7X5NPOye4xAt98Dw-morAdk4NPKz8gpA7b5MPO-0HTaZrCJipSzWseWb6QpR7OHLUiB0tBNdqIuAyMRx1_0_Vm
}

sprite $svc [128x124/16z] {
xTa55jjC40FWcLt3yjp_j3-K_Uee9atnUnnIG5uLvDVrbyxhCicFCdNxe8KVaZxiYpw9itdOnfZ4qMBV6xDZ-hv57Am6hCAbsG3sEz1Y1sGLYb0DOB-3qEo4
4kHHiTb9BJvzqBBV0JveZtlsM9xjZZ4JZZh2Eo2atpwMLtlCIZXecUz0Ypqkwuc3bgAe7A3DQCgHwvqg23OPcGfaR9r_pMDHW640luDg3a1-D8JVm6GEfZi_
VvtVwFPEkdFrPH6isJj3NWdqV5p0nIS_mEVoynVuy_Fp6pnz-Fc6ju-Vhx8hU-NFiilO-NY2b9wF2n3f-RW0YPwF9wZxvITGFwp43VrFtEXsmC3ZSnnutn0O
7ru-dg1ApySJPEnyF47gcczuVFZv2iQ7b8ydo7ppYti-Ba2av-C2hDxv4OuFFpyT_lbh32zz68wN8XZ3SNXyv2hSggFZC-GwFJf1rN3-bUz_cuydo73-3AwY
03wW7fmWfUK3U7pu-Gh6Xv2F9cZGy_446JiV5o3Iyt41Lde-dg1EpySJPEnyVB87OZw4Jnz-lgBno_6J44ByRDW7zUjzN-_yrAAsTrz54pWT_n-xJ_aP_Csx
oew2Fh_-g7nu_FBp2vW_GZuOmChFnm73FN_xE7NF7x8HlVDLjbRV_0WUGil7Bzuzyi5Zr2s_owxebQz7_l-hJ3liKyQqu_F-JJiQw1we2SKYhtMZAmAeiNM1
ef6fO8jHHNcdyBk7TNxtC7xtiC3l7ZORHP2ZChzxMBF7PJc3t3t_3if9Cx5x_XsSvRp6xnusx25D47u7vQAPtpqiyRk7DNxtiC7j7h-3SjD4x1w_WvFSL-so
94-ezEfJ_aumeZmcBkcaESWluAz_0G
}

sprite $user [128x124/16z] {
xPdNeiCs34EflON__zhkhTO6az2twxpUSJ8WmfBadyl_k5HobAyYBlp0z5zYt_Y55ULXqiRls54U9EDafuVj9raUeE228hQuXXkAfRs3e3anmG-GD6TWdr3G
lNoKCA5aXayFMejNm0zQdi-EvGGQWw6OyIux6Tbvii6WrL4C1gsEOZ1eTJId6BGcT2S4RiACpgntKxnS4s6CaqjWpIBMl2b1BjWWiCkW0qvgz2yIEt1ouGyu
c4xUm6zL0YiHbxTVGDHy_V7psuMgM7rBMFX8RVahF1zMdiK7C9-b9Myp-Hayd_5dukktz4yYAfP-4Dr7-NtfS_Ji23ypWPhEx_kneab_ehktaUTFNkNlTFaq
iYgsq_Z1bWyQEwh7ZPy8GDNu2rqK4-1QPMdycvxK4-0g20f_m876l-N4Q_m91qxX1xlPRVpEE6ZyNWw6uVjdAWWFVl-OnFJHvN-e_20tNer-KaqwlplAH-Tt
c-Zq2t_YDdwDtAXkh_HttayiWHr4wSTDe9d-7zJ1nWGJW4Bu3qATQutYHVJ-S54-1iz_TnK4K_zj1NbBFn70REk_hQ1Xwx-j83pldqVvwFmXrJxcMdEqahpU
ZsEOylvG1txF7iKh_Uue7yuVsiQViggd_6S5RTuV9ouOWVVt-_YXgM_2XcVza9y9hB-181_-km0KqZz0KKb_a9zOdB-397F-AZy1oXz1uoZ_bX_ndB-3fb1-
o8z4phz0qpc_an_8d7-3Pd1-Jxn_Ix-xQHzh__6VJVptAOccVcAL3ai_iqYteP_u7N64VqoQTk_V_FvBZtx_9SNCJzv2zYVzHKxMS_v1d3_RtJzX4OTQTlTl
W7lxL96dQFvdV-B-DVDVrlltpqiNAOUJ6loBnAPEL80nJgx9C87FSuSXcHeOPdHXW1LBABnTzZWIJF32qcoonpFnSPfeCCxUynaK9SamUyzdC8cUQPCzdeqF
CON0C8Fo8iacUppL9diyqoPxFDisU_OPb3U9Xjcpps2KznbucIgVO9X7tsHFi8DyZ92hakJb7y3_V0i
}

sprite $vol [128x124/16z] {
xTfNSkGy30HWW3dZ_gVzWxED4eiQchtnUzq0sUf1ZmBzklvY7uEZ7yLrUTBC3va-v4rt1EQ7V38S0GNHXWTFrm81H9c8T1PdKN17m4KMPAOZJ1K5TmIcoGt5
qBUoJMvgzhiNBVO8zAAzhplQvcN3zb8Cicjuy7GjR2xQVN5pqUwBcujsN-QzHRklC2tW9iUKpS_xFaDpJWvZcfBJEk0pFsLfOeY2p20B05spea0Jc0J0GK-_
bkYI80owOWHYyVi6VWStWGXqGJ0QTljeIzs7tq1PGFp2wSTN40lCLlcCLakEmNlddFsFSzxxa7AfVIC0A-NJSd26PjZwcFjZ5THbOkHWQ9aDvNu5oQMUBDtc
yf0huqxvD4yF2bqkt2WVJnlIUWNLzV7x1n2MJxyvSlkaBM-VIZluAW7hvTEFt43XrVAf8ZqmFO3J4AchgPOBvAg8j6Ze5fkwY1HZLojeyaarJvjarEGDBJ0X
j-UjnPDIMIqVUc9ZaoUzvkYTPLACTJxcDkH93MR-__BYXU_ddsl8cz5xQwtMrdhlGvwftvDTl0nUtfJ6XPHhwqC-6RsLd7GzsiKAaYiqmSp6CFCZLxHZySg7
zjYr_pZWvnjLFh3vke84Fx-fyi7E5rK-uFcioWSqNrVGWCxN5II0-PhwI-3vhCe7Ez-gyi7EJ-hqd_p-hGrLFaUlFpIrVOvUVsayAR_zwyyqHEQC-lbFNdzh
hDhdvFq7JQtVvVilwTFz5_Tw_sN87KNL7nQhhpzG4VhWONvXpO8sr9x6OlNa4Kelj8BDdjQXsTDOKFh5riPcJmlOx6a5_lWBdy524mpE7Zw3J7C1cpsjOBEd
TMpsD6psD8FDdkQnp_srZCeUy4s4J7S0ieVD8Dta0Td3PT3JVGsRFMsSUU45dq5waCTcJqlOx6aDcprj7CWUD8EqoHt87Yw3ZlRLlLSzzrL0z0zS4mnBtyQ6
T9Ctz0luwry
}

