sprite $control_plane [128x124/16z] {
xPg7ckCw28L1lSBxl-r-KOgSYU90ufsj_orJN0wI3k2n0dyk_q4VWuDVXUiyQEQNg1FVw0w-6Kzy1trh184V8V-Br2S1le78EqJukM3cmQ-900iBo0W_1LDv
y6iYC8qL50E7OXihQVReGlkh8d34Aeujovu_WVm1fUwNHH3u4CB1XLPFVBFG_ge8iF3XP3o-q7BnYUGdYoB09X-I6HdQvH4ScEyKyNQDF6G3-pYfUe8jjh8G
X5s4weyfROMMxP_dV0zhsyeYiB032TGzFCFa3ps8SlKrcFWby1mhKfT6e7TWKgglYSHxEENoJtKnOUz62PuYKFyy0dhkNq6-7n31yqiEVe3Grk3sHicCrS8p
gd8ulAJ1SqndPdzvHa_22MYwwfFWLSAsbEhgJACpWDCNxB1_Or8jQDP4EqT8EVX4oz9UU8dNB7zzqQyhteAtmeGgckMF-uyhRJDx09yOmBxHh-iyZ8lRgWoG
zCkVcBQn-4LyyXRKjTbl-ztXn5rQ0fFSVdc_M_Qxz6aeMrEIDn-_hyzJaLOtbXimg8j_kPkViBnn4xUWAfgf46P0XZRTnAwBHHAt856f25_CYvwuEW2RdoIh
axOWt0tK93jEeWVpOkS11GI3qjkohlbOPew8RcZ5rOKTOKtd9QXgFlLPyjheW4-uM8AcgNdXiyV2HVtUNUOK7BbfFdaBabSV6WEtQ49dhhYzg9ZQknz1Q9vf
POKgp5aaCxE-jNCCzNfEdC5AMv2eK9kfR-zBIfmlAtgbkQRI5cH5Dfs7wpJyN42pw6hY5YIt7yIxh9lN-xMdz2t8x0NfsdJ2HR_vMpcYvAqBzN8wnc9aBKYI
9NuE86vBMdNC9KJQ_DuCM_JJVy8M9329cVfj6wjfYpKlytUY5YIUepaNrqc7PHbhQtt_kWNXxYakvthJmfFATRxQmcdTwrkGswb-yzurE9ylPd1jaV5jvfMk
1UNNZ_xXwxNbiOYcEIEwluBerVYdHVfLtomUZfOrsBn-4IVOkS3hPWhMo-yVzVsg1c7dLmQmWfULPZhRtT9oKMfHMF-tfqP-1k5s5UlNr_JkKOgy-9MUtJNe
O2k9zk4TNrajT3SmyP8NSImuQMrfkvhfjEkz2KbEOh_tfehCOgQ3m7i3sPw3sMlgvBORPZqNvYxntjQ0uOqTWz8YWgTH5GsWJNIrWnLvRs14u-SgUb--B0UY
yUFxcuTj9qx3hn3lUZYHVXVLlKaHRtgHWJLN2zekVAJPWl9pEopnzmzfSL7tPAjAsbsZEN4qXs0NtfEv6laz3xhQ7Gom9AFn7YqoIU116TZL-w1Hu44nzOrT
o2Bme02jzoQ2V1MWyvxMWn8CosTIxy7ZlJS90WyUwxtZFPXK7mVIUz3UC2i2V-HYv4E0_EuCMjQJWa8VZ__CbvVhJ-_fFHWGN3z_DNc81CHmlYL1jhWz9FMU
t8CUQtDcVEtf52MQmksaP08ncDJc8SYVL51UGQVxakyqxkqiCtfcjk6apuoEUHw2BFIUl81Mw9kl4PWndTJyHJ_EGq_ryOC6Ke0sNzE3VjeUMkiRa9Bruqyl
nnz0JbkiVsOcsowBx1Rwyz1AFuE6bV_Bnlzreszj6p_CGmlz3YhCVluNtkWNn8w9vw6LFYZnV2W6j6H1Wn7ZGKyxJZ_3Ez1H-WtUmYnaFK0uwvCVPfjzY3dY
-hEpXtts7B1mXJJqhMqzGT_qeO2b9sXoxwaVvaP4tWnzeZ7ssOTed6wzs7jw3qAQ1Rwv4U6i0vVoQmJUaqEF-lciFtQ3j_e5peYzf_SWnDlusnZj_VXhFt68
zzPR4-CdRq_w5OWvR_N74mgJt7jw3mAcNix-9uXKdF5JdmDMgfXaVx39gTlr3xVyBmYECeIfF_B_JZx14THZowwUy9O-MJWC6z89S4cAD_07y9yV
}

sprite $etcd [128x124/16z] {
xPe7OkCw34G1zYRY_gVznL4SCqkFm33bbtrRKbH04WECYkdVos_On-3eft27t6ZcHw9tkNCu-cPybu7-hIC8yYlT_q3qaK3VG1H0fA-5im2-UWHSH45c-X9C
5S1NZy0qMQ0O-bHiaqMQ_Un6-rCZS5sM-Dosx6M3xQOOP9VkDwFl4pORxJvniz7k4pSRxJwPFx_HIl6fwtTMZO2RVahcLg67VWIVMEyzylqO_P0DOPmsUXhz
GPqo9eWoUg3tMALaZ_sQFy9SjheHM09qHNHFpp1vKuEiYOxW99U0mwqgkZCq9O0Hw1IODD6RfFdWNsKPko0SJZ-ERkfJ3UUtAuw0JfHWzU6ynt4A9XtPZGSN
lXf1VwxVYthdAY-qby4SPoioZxdhbi08e003le0mXxmIHvqLyoXT3ve9xC4D2jOELImZjK_CleBfwDFVXl0g8bo0jjPzqZGy9a0zhNcVHNS1kCRwKWVACcNb
kcGi0IeonQ-alz8hLHlUN1HKMKb_VDlXcCG23giM01Iu1G8fbam2_NL90Eboh75wayzfah2Jkc11nrMnXd63VNQxa8SHgoteQbSFJZ5MPxxAQTURZv-UwZ0q
mdMkMRq00vOAzp75M3vsi1HeGLWgVROvNzwvTCQY3jhqbucG8kpVumevhGKn7cY5ufq4mwUL1VCvuu-Bpzxpmy7Ul4y1hcfXlVcCJbBV0iN7uajZkll5URts
scECVyPnWyiF6qwwre9m_FpBDF93Dlemj241nw85MI2_GV_rCQb3YVEmsw85nOi-CKwipUS_BjD9nSB6CfsipqDIqsFbvA7TnIKBml8RqsZlywoF4TfuchXc
GURv89dPXlg--zcKtDlHCRdtiOvecLbXGQXA_CH1wihZ4wq5rUVx53XmV0FLLHQ4roZ2reKzf84dUWqS20yl-kNFIWjoeFinR1suY8F2We19nDdXsFz7ZF8k
gAFkdr7fGX4Vq07AfVmapASLbVSlQLW_t5n1b-vG0Q263RvhvEkdhfsd1PnLsMyNZ_JieDivTLv0WHNlAFrGlS22191Uvv3jqDvwJS5POunrFfOXE9judEep
0kZ0V8PPi4XXe9E9EkFBWOSWGFSPLHJ3H69uLgPSxy-grum7i6diAqamHZL_gU2CQ6UlV1BE2oyFc-ASwiLIl_LmwfE6-TCYt82T_eaMEQIf5a4x14jLbzvQ
kJoRMY-12IW5kaXVVMjamp26w9W6l5QeG8BOymfmP8NsEZ1Fe44O7siFMsXKQd2k6M35shUGPV7DwJ7fP8lQ6z7LwrmnOKDx7zDWV7f28-gLtD2WB-r-kbRY
elRcX4KDih7EyfxsrZM8INg3_f06xHqp8-nz1eHbbyqLjFB5C662V2cMhYYo1TaLxM4DOjAn7B-G1b7HgQx6FqY54GrrFJxlV-Qo1oPsxMp5JQHxFjy1LaiS
K7n3MZAu7uubCJLfdcBjqfb2SXH46d7AtfBTqDxbPNwuRUbaHT9j_SFjVqU7kDkcy3H-fXLa3fl-Duxw6P_v9gpQXSoBnEoMzh06-yC2tU9tSlTD3kgF5l7p
ITZwmhd-npt-WU9ZxUars1_MPMd-dX1w3JBrywt_cFzydFblP87srkWp_QTR5JgHT7EASFlVKplrxsVn6tq8Cwt_K19J5IbaKtkjVozIYM9sZYtGtY8Uz3yH
JrmU-rynn47O0ksjacG3f3sz1hV9j4ENJHfjOMGJsiJ92a1xFw91H_jK-J29FeFw4zBVloVebZuD6z8Ytj2_WD_y2G
}

sprite $node [128x124/16z] {
xPg7SZGd48Hdo77w_P_MOQazQqlB_SCXwPm--qyNgWbDpmAYVox_mpu6H-_2THmqynPrmOFkw8VnWWlYw0S9-8puDweF0lq04K-8zBrmnk0jBU021PdfMp0L
WxUqm3GiK0nzARPXaMQ_EcZVrG8dME9hOzbZW-rG3DX5_7lKzsCvGa67XhWLj7Eo8OwoqOAje4rC1xulX-9-qCfG7xW61OL90JUDUgGhja91-PhrBdUEDWKA
33t7AImVw1wZyIpJKtwjxg-p5Q9TMZLTiUQrwZOTNf7Y-T62X5zWwGcoqlVmSAfa9cqB2itX1NLoBJbV1CSVwT8mmHDeZjMh3wjATYOs09akH7d9WKclVYwL
5e2Xhss1Mvv-2KGwVSqi99gY-89EVz1nXz0Ci_JveL-VwET50mRLWj7h-yKCRckFBwuzzDFASWuqONczU3dqCozrg2dIHntO9LIpkfwNQb-crt7J4TNRrTCD
7CAbrpRw1GDukaNfrhFizUo6YCzoJ6kooWGeT0ShLt_gbsT0Kt3I_4u2M5rRGuqkL8oo5uXAyIurI0akDjOb0ElD6kz2gYThKnllZX0mxfW4epE0qwUrlG_9
d81J_q-St9j5z1K5jz2UVi4TeYu-RLC_u1PryKcR-aPTWgeYAkxqwqTzLivgs2W-NavzYUDvzzHlLjkjzcBw3EBGJpJWSkYBNzXHA4j5fLiuvLGCFR3DjRXN
WlB2iG5RqgCiGGj1nK0bDKqNwmj1xSOR2lGbo2uy--Hnv-GIqu1pTZH1MOAYib2dwCkdjvFseNvULxg--462iVdZy9HPITUN85KZnz0BdyDgOtDduyUBXWQh
9SXeoqHvB9sA58uavKEWZZVTQmaKrFRhftCYKiI1b9mhqEG-iAoY15Lr-bMOKxzJ-t3072VrIbM2z1lVZlZ8bMQ1nez-2X1VsmMn-j2sdAvCHn_G-JBGfDV7
huk4y7sLp26qCTfNloMi7AhmPLafotH17xkDRic6VdKe8omSgFfhH2WtV-QSX7ZZa8OIlIh-hk6AANwsKw5synnLFhc6k-8WpguU69UUgCxqytMvpc7DgMjd
kiV4t95kdEuKthkcUySJAirfZIwWMSFgm_oaE_HEDCN1NfEUTTuRYEvZS3J3ebtaAYczDz3UEHYQa3zEZ-befFFUrO3XrJk3D8Bemt5hlBohx9TxzTvep29w
ZZ7BnTF3Uyh-ywlNX_amfpsaip6ZDgbCDPZ4hzw3mH-_doEKnUkyDoWBbrvYQ8eTGQZstWclVBhH5FDvV1BMvbIsxYvJovEQgyrLLhLNWTfxGXSiD1xKmVs5
Uz2uuy5rxrd5DaMTWtlUE-aR7jpmtXTxq61j7FSzkE-zaw3mO7bEN_FUkWVt2JIdOvDD3pFss5x35jyCV-FFV6ruRzk3P7UzTzA_Jx-GXc_JxrlbUr-Vztxc
qXCYaqdZ39A9NJkAYIKEG_zyzHwpUMOSo8TQ7ML0c699J0ren2bxI_RowiHxMjf4_vX41mIgnryjuAWTxraW77yLilltwFVwzPnfOepLB223iobiv4ySYS9x
wnuCOscIWP33UAMTVoKBUJPyj8X_fjyV-hN_fT_9ri6Ezqxo2_qtYcCiDMsk3pxd7nYYxPZ_CV6Yy9u6cUi7AeUeE_tlX_yJ066dsBifC7FzSwLte1B5x1oF
zH_-VBKglAV1J_L7qldZtyKG1_0y_mozIi8NuEbr6hR9j8DWaqPR66n2cpXiOMYNX0qSxLFnCec-WleEw-_l2SJIbs53MiGR-WVmFxy3
}

