sprite $c_role [128x124/16z] {
xPg7aeCw34KbDy3j_l_VladpR9woZ8KTltgcfXwoliWh0Vrp-H_sMt3qL-4AxcJpbzWh6iNHOdp56zNHGW8arI-sIm8jOCC96tqNFj1OVmGSqS71z1LCGcFz
4PWC1T7GL6o6acnd5zg_wWXSXOgvPTb3mVIY631AzOljaZ2vqEhPXWhj-YFWYEaSh2kqyubC7N36ruZAytq-Xivn-39Cf-3R5DqvFnzB9rG8LcQGiO0JluLW
QG9tBC1DNFww7z2oJplxIY0Y2XKgAls6WORaMj7ASm8OBl-7RUEC6fpxbrs4sEmLdOJ1vS-119eWPFeCAvTTuX9w6DZx3aEds7Yz0XqNbbt28WW2Vsdvi_oO
tOvZip88vSeMnDgouP-QuhL9khBvr9FbEfH-lh3vr4zlZzkU8MiwNzc2YiflRtPk_R5J-NTj_AG_0Ud7eMILlrxOVAemj58G0R363v84bTy1-Qrdy2g_8K5I
-GEGth8GLFv00epvDvK_2pqh_6pC1fJmOWUm6yEAdKpudSAVyP53uMTHpTRwHSd6MdzSuDS4m2xrom1ir_mvbej-gzfyRaX_jOyZ5twZxeAWzhVVS4Y_rNP1
Hj4sD7_va-nG3P7KdOzxzxSYQgH_rtP1ITMtvhSC1-bFsYu87IJXZxS7NAM_AhiWHW_2ZnpSZiQXwwFLKp_NMtysxHpcG0z7hp-Z1w-UktJwZNeGXpvyd_z0
7-gnM-doCpfXzTJLz_XtzIIsA8V7Bdp4qWtM3-AcNiQ9wa6SKSsk9bv0kF2HJETmrK-2m_Zqj96Wm8ZVhojRaltA99odpQy3L5mSUzj9-YWoExO46tImICrG
6JW6lgH2HvBpvm8TQUp2Kz07_toSfIKxCVdMm1V38-VmlDKPLo4ZBf32bcVTZb2mZAIOFw-x1csn25RKpwLNm2CM44YmCeEHJk35sLkVGQPpmgBipS-WfpgI
lKRvdZzI3r_p5-h2VClF8_TSLizazfysHn6eWObTVlhRGqtl93aWg4nXTnJG_C7jvVRq5dUc_F2tXwhiIJBafnC0HwKzTcXF5x8FVxX_ifA5u20DSkqODr6g
pHy1W1WtBDMxdqszuQYUPa-VmKeEFsc_rBL7dchz_GyuUDzlaVu2e3H_klaBsVJWF7lw3DQFVldxZQ9ZKcImhVzHtlpWr_hZiVwFXQz3sPDDKSkRfmpaylIt
fpEvL_xtcvwT75heCP3dlx-lUVEt4xwqyp_S7gQHx3Nyf_htxdyKF5_Ewf-Xg-oOWAVhP0npq0WLWsGQmc0G6iHDlDzvVGOTZPDmcPrca5P4VtvFK2rDmuPT
YJVq3-1__W
}

sprite $cm [128x124/16z] {
xTc7Tgim60DWsNWmZFN-JtltfbKnyDjtVHrdveWsYfM1FzT_BkOKC4hO-KdnGz8hlza3EekLFwa17IKUrTWv_IYXWqmXmvPRA5XVWLjvmk9WmcyKhA_05pPO
FHur5JOgqzC7xQWh29LDdZsM8--eqU2ewtO5YOz81WTjcsnmq5fUWLlvkCKr7BGcLeSJNA6PjU7nRiD32pJc8D7Q3YNJt0IXKh3le6C78d-YOj_0cHs4nhj_
pL-j_6pE9nM-O6vyzCN3uU2XwVzdnMkyURukO3BFrpSlVV8JNi4--QNnzAbVyQjw4b-cjc_W2RImapXeU_K4ENQZnyUU6pC-Ue9sMjCJn7xgoV6vEyUbeO29
miNZU6vu6R2Pv-i9edM-dY3NDPzwVEppNSFuN9_ZXWbYN-lWV7OV7rs0pCucDJxz9uYzLJq-zlJusFDYV0psLqyGITlpLq-G6v1FFJxs-KwCZq6-cg0w8dyz
rCzWVvMEuwCBa3d49CQdwmHnZAh7nvuuVNeMC74GF_xlr-jp__rdwN3ycht_g0_WO9-l1t0RaP_nNUsVlwbNt_RvLRp-idd_MRy0psEsxxkL7UMnxpzkOzz_
tiMddoC_0KsTkpUcWma7FJkuGd2TkzU_WmvQik-UjjftJzljkwVPTq_pzjtJ8gdLwE1daX5C3bFvyblpE6kXL1tI7938X93B0XzJMU1QkgSLAWaRoO2T2Oba
H22PzAqMjA3Y74dkM_ro9Hdhfu2reNitEbWH-4N2JdB6zcO-XCOExiVyel9rzzexMDlp8zgLj-x_PJ-Rl-2A-dh_Lv8HvMH-mIMU-l4VUJ8V5qNgy-zaliTL
CnyGSLtXRGlkgBofGB7VOjmK7loKgNy70-xRUDcC9spcrJTvJL0dF6PASwFeyGVuxpq
}

sprite $crb [128x124/16z] {
xTe7TkGm201GKBDLkVzfjtZobbHBFCPcszzU4ZmM1g4C_Bd-mxYb05P2fqDp9j47_T83t2mUqTa8SAD47ure59qbkC569pQu5cPYjry15bgG4IxXAh7Rhy0r
4YWEdiet4ch-sONMwWh2897dbkL82kgYc4XhHAFeB2aBhTwcBBHwcxBGwcNK5LgzWh006rscA9ztFGVd0bqCuHHThUkUUJqF9mOnWnn4kW5ypHEpoC2TRX1C
bf_j9ayV6_0LHxUOxpUCQd2ZMoIJvMVDflgmIU-pga2PRX9DbfyLc-LdDis7uQJvcBIWJdCb1OUiFxRLp8LKPIs8qSn8drvoaM_Y1dpaf1VDyUNZ4yYRJuHf
V9RaBQZEjgsI-934BMZj0_nUAdiiPcLbSql5j0chJra_YAfkvN4IDXydcKx2mY29ekQJPTiZFz_DHD7o1rb_wFExLKJnfUqvpGkAfFcqzyF1RFTSuIT90inl
bgEr-FmVkg2Uz6dwUN7y9gZcT7VyiTPyU3bH4BylJ9E2SjtVlvoDiVrzlH2qeBgmNuh22IiAMX2TIxBnBA_KYmOCbmeQ3ibyXJGXcNoIu6YqB4upA9Xy1i8X
DfgeVdKt7oNdBXLUe0ji7FyKc8CNE2HJ4CqLmVvhSQLaaq_3zVYkYwQWZLQCj1f_4vx4TbhJDpUFx_SXFOYZTRtcdHsH-ivA7VA3E4T6kFhOG6v-9jplyVgH
Z73vDL70DW4HUFjZO0Dci08Lc44A3fF3FuQoddNzLo6BJUwnRf1xDZdOuLFU9lTOkZdtR78m0JF8mG8dq2RtcBV9FPOCSa-RWn66ElTOlov-WHMNnU-mn5qL
7v_qdiiH4Tp-21oWK8I-8RWytUwlohF3aBG7I4GHKjWxHGX-tn2oClTOenFfsAy6w9GUM-Tub8r-ld0P9EW4ucCI7fIW7F4VltWOyjoJv-20m7UYFU9t_jCN
W2bpiB-Etpd_ZtNHvXxBIw-_hxt-279jilwvS_nAHqOEVUxDXwANh8lGE7uuxekR7FKAkVFdFn9n_91tX3B9FQaugt-SVrp_zBd7zWlUxIBII2s3nY2b1YgE
b40fa8e3Pf230VIgxgsUUjKYzVKpmV3mD3xjGj717-2_xm
}

sprite $crd [128x124/16z] {
xTc7ag0i40JWPWWceD__QIzjNaeTHkMFNyLBjfRDW7luv_gVYrCA-Ak4mZ-o_2NfbUzAm62nyeiQC51YgyR1wQs40IOUcF0ij_34z6JwIeN5uH6oiJ7k3YIp
mogubS_ibFtTW_QlkeDGQLG2BekqkpuK4w-gSN1wArqSjDTD3mnQRibBcBBf3guFsYpDIS0m5Cs3TiKxLwYpEYYup7CPdmYrrhlMkrYRAZWMgB7XA-ev7BAj
w8rgvOur7_3LJ3sF0vKgehXjImSTdyydzlaH-GwxvX7v0RlgYFovV_NbANpHz2Py5kVA0nMDaq4QqMis5J0fLgpIP9d1-SOlgcmu3_MkL-D6ahkcpmORxkkw
vGKsfNi2BGFoZzOJH-MlwjT_FLzV03yktm6jULn-05fbNFuCj3Wklw8b0_E9LXgPBsXi8_CJ6XoPdzlfCpIV-lsovj_MsQFFLdwfwWcqyCmcC0YhRWkYGeI5
hvejY1e15gwmPVhogJ2Hym9CL9bXifmUgWjL2apaz4cev61IJrwbKCd399yKC8tF5zCFS0GczMGB8Zbw0UPcytbk_SqdMr1ujlxkx5eBTI9Cyjd5AbKcM4W-
_Gfwy7-JPEOUvUPJVyjhH9zb-oLNJPcc1ogFefzbPMX-UsMEp6-7cGpDRmiOXkQt1Kos_BZcafTm8LykF7-gV97zrUTtXlob6QJszu_QdJyRVfonFu13RxvN
d0fAnsQwTUPlYesfzEncjIU_BKmsv6_D5TNvaT_rvrVjzzUAHj8SIpjFKbF7aNDI7Cjzxpb-vOvaoj_OC1QsYY4_wRgdwc3rtVb9znMhxc2KpzeZNP1FVCgs
KtpY41vxLWwGiA_mSIiEE3wju93dmnoEfK7TUw23y8RkjSfp-Iiq7iilK96dyXrq8e_Lw20poOWQi9ARXqkd-GAjvJZU8Sq1YOn8OIxCSFCI_Kb-Wbu-lj16
Cg0m8V2NW4mo7USlwC43pl6NibMcbzKAUMcNx-YUlOCLWQyIygVVECn7mzh1yZc_a2oAV46lHVNyHVVy4VtooVjVocl-w_lF-_cB_OV6hTVMHUJN_DV-nzty
31CvNl-HVCtVW6a9mUtbmoYUpR_NVAu2bxYNBx2QUOC8kypB5bnHUL769SABS57W9OB6o0u6NBVHRCOTjh7LRoLQL8_R-3HtYe9_WF_z1
}

sprite $cronjob [128x124/16z] {
xPi7bgiy34RbRjo-_Q_sBuGCvON89Nxzdf847-PIXEJ2qA_BNuHnLjEFGcUi9Fb3x0LVP4tV6LDmecZwZbXyIp4_oBvZwJlWy0P7Sn4B6DnCUq05Yw0fo0Y6
cKSW4ne8aZwAIcWagKydsXzr1BgWWq-bPOCHYfcGwZgEOBgzn3CVICiE3Inq9h59aK-qu_uTDo7HSdu-AVA9Tjo_4mHL818mnm-4ASyxxz-HZ5vZhX_CFS1i
VsQU-Tb-A7f3cUddOr1WlXzqZvhgvoFGVm-_Pcx_RB-dMz3l5sSoRYbqXyHtWUblp8BFmGapuVj3-3ua9ljCXwbzS-0pq88pwKp6IavdjgtBcO8t67e9SvdC
ovq5at_gIv2OwkS3G8twXLHIxFxM0F0Z_XmB7kHW1UVNz8BSxx-IRCO5lWIXty_3bo3Pvr_m83ejrkDHPiaz6SZs-7LvoCtbN7nfBa6nms_l9vjSQIn1QFBl
rpwhZX5qOh8Fvz_reM_YY2q-lD-pSniorsUWfTLlzX_yM9elGMZqYwgPdTj-Q1ZrnqiQQ-tIVc3aaqRc3yNum5TI3Q5g69pHZAChCKPDLqHL2Vf83NdzGFYA
tIMQSOoVkm2Z8nzHwwV0Hq_42yePR3o-HghsQxu4rTnWj_UTBhipVcAVNj7cLm1aWpzo0Q3R_FRIoFaz5q1Bczy1gSLlk19KslmU22r-nPKWjFaNO6dnIoO3
g7Q_R_4B9eEuHh-_EV-xtg1aIb1kzBkR-t-tog2O4eH6lmRYcrLQpyJ_LI1R_VBIUAqZMTTrBkY1RlLJkPr34V75JGZlIvXjzWV0CBr-Np6jAtlFtxmTT_XB
UbDC2HVDVYe0iu2NRhFx3dDzyfc2bVB_TwxlRulaBtyOclZBmwlOWYdG38RgA1KTo38wYTA-fXA7Pt4Mga3L7RsQTGToPVVPeGD57B5wpu1sYkmR_C4nLwgM
ehhqyNFB3xRZbQtyoTNF89fNi_WznY-1wba13-YYE45dTEowOvJHINAADgHP2hluCMC9hAGOKnuhMmgJ4Mord8eYZe0U39NRdtpiZSUWrpN-G3MW3zwVgGev
oozwthaiHf3qZx-fAG352X8whLlWziPpI_w_PM7dIzcLu2B8UaqMC6IrpoY2NF224c39s1WrBQl_s698A-y4BPslGQR3NX60fWnBUj-GIQt-zQjU_SSMGshz
AfdU6X-3GZoND-tZqTnofFeIuY4innP3OVlAn1uNWuNqVYNIlc7zPIclVhdwZos6ylFhHkTxl_depuSDbkB5VsmnLBQlJEnnCLWk_ixpDzHEEjx_9JzjudcN
SV4VMypZn3KL9lQuWTCMTUPnjlk6HFhgFxQOzLgKBOmITI4FpxzvshwUydprxoshNozURCMCEZ77_BVPjYndCgx-lMNzkUS_IRtuaOI_D_MJK8acTfJQ7OCy
oPFiNoGShyN-_frj6aHZ24cZU0oWQPo8RZpHZpo0PSe_tFNF3VIZh6_4IFe5-Ck_
}

sprite $deploy [128x124/16z] {
x9fdekCm28H1lSBzJxkzQ-qCRbk_loy9iZGm83_wS_aFnvm2_Ih2r0yCzqkYYtvX1dgOAFeTykWAagv8V3ZwIg87oBf3fdlXgWlFhO2R0bIcMt1T0UvQWHjg
e3cw53_KoF1N5zfVjO8WQkBQiXpr319lA7MFhI3f9QGR2gsDVAhGFhy2RdevbGs5zXOQ4m0FlOs6vFkjEDedAC2eAJXc9lOXjwaMc7RHLqXTYYgdhZ3pLCwF
ZMh6MHJ4qmwYUtHFsoGvhq4-vMP58MWRhzlKgteaFl84uWa1gThXmF5FliuoYptxEW6W1KHe2xULTMJ07nTWsWcF4mxNuA4_GvXifAFzaA5WSKWvv-Y1B83t
az7E9LJHpupCj30F2I1WYurp6RQC6cH3yN18ZIks4uZuyJTCMzCPZ4GRVlmC5cZn5YE72qV57SuRDe1Hy_5uOel35H28eAGPaAhj7owW_3AKrVPF2sW-pZOF
CjmDOLLxuhtXkgtUQ47zXVgJjRKpMj36fvRrmOLjc2o8NsGVAq23Cn0o7xOEPWBhbH77iD-6C3h9Hk3u1TpDNhxmAJuxvtqidsY81RqQ5VlXgPud802FnhVF
r0FvJZuJFrl3hrtbnCxVFjDtp89K4VtRHxg6MP1JFPF__S0y2dGMtjRGh1JKWlfhbnZscRR05gGBDlyJ-nmsbiqzu__HFWOkuaBw7ro1qU0L5Utey8ucM9e5
kRob3QPc0HmgCgn0hm30f-jIJY05Eb401fwBuGKCDFowkHE_TKp0px4eH5cFtpx_hqlbgHYoce_z_cFLqr2K9LSizpyhQGcF2J0TkB1tCPKYkfRhhZWEgXN2
Q6lbRU6LiT5ceBrLewOMqCbseCsLBNo3YtK7kYixZC-s4xunmicMkmNnLyVlP9kkwxLlw8MiXZa3q671y85dwUwo-7uxcV3td_4IxIqk3B__3IUqjyAACahq
3X2DSLxr-X0Cl3Yw4GzCopUIQ9kfjzDe1zQxcRIBVrPxA-bfxU4QtDwSI89gxpNpllYD46wBFmd2tHMVZ_xFvTjshK9BGXW6JcfBBV__kKSQU7thItj-Doiu
4va4pHOKb9y3WLnff39kuiRVbrYrXc7lNCeTVOsaW9RehUoF2QUq48gGsf2JHLJ-lYJfYLb4FAIz-rSMhaq7MFahksiUleqQvG_8ac9P0gDRtJb_Ewf1tP_k
cWmB77WbpKh3ZH-q5JYhaGn_Htj7DSXmk_uOFK9UApMqKTQLTB985uldP_KJx_tMpbzXis8NlSHTHklEBxGMQrneH7iTyQR_FJ3t_HVV4-DqLg37KIxoNrh-
rMdvs_9lj_pJdl-sXO-eOzhhu7FzUzN_8lJaP5eyhbt_gHdfr5zhxro_3cWm0wVe76dz1wdotFXTN4VJUVtNZJ5s_kbtpvEH_aUN_QzA_qjd_S_NlTLEQE_y
0dEawJF2XFOwoY2_x-gBc04FyDVeUl4LJC4Cy6TGJnmcuMRVTvx5CaFlC8yyJhy0NsF0lFJdhmdOujrWmt8Gtk07u1zl
}

sprite $ds [128x124/16z] {
xTg7ifim48NXeow1q7d_fqs3ySJZc9KkMfFCv9jsAx_B8hdXt_MV2IbwtCLl_ANQM-gD3vl7XuN69ytZWo9VjN1ZVHVn0Oad4dIPGa7Ih2_iK0nKs9K2pKjW
AmSi5bEvoa7LpLvexxe4ld78t6Kvi9l2eXXvLGlATLbKM6Z798M5TanIM6Z753EmqAfO33gOIZKBH86gBCvvAZCuHLdr3oj_QVv9u2uVtpR-PhjypWCFvUZZ
YU4k_l4sTJZHADg6-xPx1Wtr-yHxhhCVX-RDTazW_aJV2tU_TZ_ZBVOefTGh_OPtBA-J-yGxKRKlhy6LRzNW3zmL_sJXpX_2nbrEAVS-7kfQjhbBVpvpUaxb
-eNL1wDzI0TxvLNxyWfKplkUtTnvFmXtltP_4Uv-xJw5pKUzRuOt7sDC6Ek_h3_I5hHnghD-xXk_uCU4sjblVPkFmI3JsITUnGbzzFOjNgoVx4Uye6PVteAC
QbyU03-pl-ISd_hoeSl4_klw8sz1_6n_kRbFF7EgVVdOwTDzXoVRzFwwhcVzZ2USsvUVpZLXyz7kKzXyrFjMs7okzdFE_QyAStwVWYfiFjfz2fkFUj_WeTpH
3tXea_ibfJJoOZ1dzTSVDafwdwiRtNUi30xfdhx3ORkddt7Wj7x-OMMdXfsTr-SGxBnsNpX-lAjl_uxhRsw-_z7kwIyuUEM-UFZrZdw2j04637BijtQyzbVo
aC9-JRZasap7Euzj68VtleU5Bp2iNVWumlQv_WgyCX_hRyBPezqtdUz_hSF6Pa-OGIKHxsrKj-24eRPDMi6L6PoBLEKWMTWFJk6ZQ9jUVq4FjVw6BbQhR-Oz
WriTJDpxsG8sKsRHgr1GON89xcS_8fGI40TcJrPvpgEIZ70yxeCKA2WOmNFxZ6m_syQqmTcxFeCD_Z5_6GYbKJBrLOJjjpxNqF4HQOjHfVFw_rIZS8C5ZAlY
_L_XU8YemkoDQzBy1pXMiuZz2i7m3Av0AjuRHrh4KkBfIgZmsVF5maJ-xBSahNyMNvKvGS3NLLvMS4NZHHMNM5w4YxpYvvtrPz3ZkfLVbZ73gZxwAiy9ciCq
BkP1mU8VyDzt
}

sprite $ep [128x124/16z] {
xTc7ZkCw30NGIrcIcqJ-_z--bmHZmA2B54wuRGxADWENMTEaDS6VwmUbCKVyAh7AKmc_99rbKoES9POTZd2KHUFadAvbE1ZbmeZFebaKlmfeaGOpuIF2AefV
1Q58XoNWMmr5EfNXkmVjhweWihofHfWbCJ0FnInMd9pJjMmSj7QZST3QZSP1QpUJRT3QBOG6LEHZ5kFpRXTmBSg74Ix9frNRCy_rXjmPS87bnemRnTA399_F
5vmRFF89foQF_8XJx94_uPHuv3FE19TymPdianzmelZaPvmGd_o2O-IKBpWMlV89XsQl_8H3ufM_l7txfQutM1eqB1__bw19t4GSgDBe-4AMTfFbrM_5j5No
FvQdI5MQCRJG78-j06nB8m8z1K3BxV70jCz_tT30bcF0sX6FLVRv8nwe6exa_V5RVdy1HSLJLxpAxosWS_dCAdwNhmgOkoVGVFl8wVXd_YYwW8Zk5IHNHc0w
YETNlYeW0gLt1TsUsT8Mh_Ft1SIMOTwrV0wUqXnZ700Wf9HptGfeNMRKSV1TTBoiXzMFpO_pqB5yyZvUxx0Yge2rRmMrJSlfU8JaWwh6hXKK6YyT3sSew_Zx
1cXVFlEkJtHPq-4zuPuLj3REYf1PtS8WNqeYR9QU5TJqgCIfo0xfsiiK6_TvQLq-5G26gPmybqbFwnnqIscjosSEUU7pXvZb02-9Qli4ckKznVBMd5IlzalX
MtuOBE-ggxpFwUHptm1ZyqbFNhZtt_Xo1TNcRqpuuXHSjiMeBPShI3ppzG0Fhlcw0QDhlcx0_Alom-_n-UaNtt-mQxuUmD4tNo_0rJTV1x1hlhwEtFCPEuDt
Fc5lzCqVRY_XSg3XtwGSu8OFLyNDYWCaNYeE3UA4S2oBYm5d5d6GeNZsu88BvDnx_Zr8k9OTUy-_1pFkLT_UqtnxJmk-lQSbkSMPGB68ICBZzs6MMm6jvjju
mhXCXFB87_Aw39WDlQSKkPQVLp26Htvw_ZQqVtDixq4A_131abvlpn7Ssdls7cHyAP9Gj_-H2r0CFLWnh2_F_dlbhqszP-_1_Trk-_m9Yga7wVMXMUJh_WzW
M-zfVDN_qoEUuYC_Fkz8QF-sqTw3JCZBH5YV-N6U28krzxJKDlzg9eJ5tdlQ9FSI-Ew2znLx_WmBjkONc0HhFeoYc0HOJM8GORVAsoRWLnOmmy1y9k01tsR8
KwSKy0VuyHy
}

sprite $group [128x124/16z] {
xPg9igGi34OJ2CYUzt_QVx4NfqsDmKlJIzKzjOxNyWXy9lO8V2-_e5iymRkWoYl5lCNU-4ubU36kyGEDu8LubZJtOhl4mmjO-805veAH5PQPziGTH8GfcCmA
C-_053v1Cl1KhB1h5FliGlkkEw36ftXkMNOym71Hz3nASvFjEdwmq8wp31RQSPR1GZjEnB52Eqv2w00BJoDDVjvrZA8dbfGKVqGgB57MW0K11vgcp74z-Smx
62Bm7Wi7D35w62IVoI3o7XZ5yfup9sSOfia4zgzMX64Axo3bNgVvzKZnA_mD_eQPwjS3w5_ZDygfi_rUMVxP_g9Kdpb-FG0qrQzNe3ZLh_SqdkdNMn3s-Z5K
vXeGxfZOc8jN_4e0hEBV_nvijAyRrNJwKMy-qYzlq-xBLiC3lzQ2Qf-_xD-bK3-_gmLnbv_4E8AOMTNVG69qlx058Q0kFuF4gtvP999ODz_dDo38FnX_50BN
v_SWu3w_4xOe1YRzUWl2JZ-qVOoiU5_L_InphVhb17WH2TlhHv6hNZyiuYdEOlKrlpoJk_r0woKBmHrVnNzwAluqu0T0Qn4UC6IL_hT3QJxFxRzw09QN-cLI
wrI_teBuZ1-DjGRXJonPq-sNBSZq-j75-mLBTFZm-BOSgDVFildeVY-QHFRxlf2epsz4yz7yIsEMj6L_YUg4Nsj1hFjDvRzGpRw1PDJz1JPGzri-WFOLlABg
PzWWtT_uW2OkadK_Rlwe-XqVuiKa6jNlDdzJ_O4F2I94fFgJ4hynlrFzh6HhkX-LvZFRRvNcCziVbEMVxMzRyr7zW8V8Kq3tiwW-S_g_5a3_Bh_vZF7Zk_nw
RvdXbmMOvlhr1fZVuLzWextUd-4FyEN-zY6_lqGFdFFzI_yAcLWmu_kVp9xemjE-VyffrJD84tRhrJDJ5Pw_OGxFxRV9SU3xlv8zaS7vU1383Bvf3mZoRAhs
k4u6rJrVKx6WaUPcJwVEpPxEtEpf69u4Zkovp1RGCrfc1uqWCJUFW5JM9h6U0hJ-qIEOo183lKGM5C0GBS7gznGgDuGb1OIoyrkVamLv2J_qqaBhCGkMsGDT
hfVNDRKxlsFc1cRiLKhuBnVC5tzQZ-3rYMwF_dovtQPaxrm66z15iVhBTcJzruE_teu-CBZljuBR_AkYtlrvbx_hKILx6l5W_FNi-Dt8YxDS_rM1j_M_3Rfk
wx-cOYEElpdRLKgR_nh30dGRxNBnqtehHjdmSZQ32J14yfl__lpNTLfoMUZgfnWGafAzqncC1d3XpN-jVwvU_hWLn-eHJ1h8dlZOB69uW8CcZkZe6Oosh44A
P_qHHcWFzTy3SfzVPcyqWuKGqBUpVXY4U0W3emGUW62Sp3yc0Bpd1iQZF_wRe5bu6jQ7apW3Ny0l_m8
}

sprite $hpa [128x124/16z] {
xPe7chEy3aPVkU66jV_TtilmDJyA0eUO-TkPFY4SOGk9Xhyl_q5-2GxVXLlvYsg-nTxu5wl3m_Z67StXGG9Bcd_OBWbuW8KL5io54f-mpBHdla0YJC4KLfWT
WQayG3RuABRo8DL-kj1-LmIkyH2VBSkUxz3yX58tEmBTFawOK6Z7M2OKsfaHKEQFasYWq4uX4ov0bQUH1_RtEHZeE9uCGOLdimxlysjzcyOI2uMcJTauOJ07
YUVx6SVOwNuz0-CJVgTE_tn_n27yXB_X23FiTp7QKJyhYu_uJSZyHGdqaHMYNb_SnRMhKSbTzuUXwPT-4mgpf2pcch-grKVtaqzDAUx9gtuz0ToPtow5JwcB
LVnQ1Kggt-R65sd9g7wFbx3g1_bh4RJi2Qe_Nvp-sFd532YZt_bb5DUQZxD_-jDYkWnKii_6-ATV3WDTQJuEdN_TvjKVxe6b2oztVlWhBMZb3WlXtpssgq1T
zJ7xz0W__8KMr2UHXV2BSTugSCi_gw_RvqNwvRxTpffFCn1-fTXr4oBzCW18Wj1h_dtKkmtN_R0dFQNmBrQ37Tf0v-_nNTfsVh42gxUWJj-X-1SWA_uUsvGM
HB_rX1d-FW3PV3hz73zCEwn0YNSgOS0V5ByMW6n1GZ_53xCUBD3bnOW_3Vb1At_nkld4wNwKbmcmy4wSufTwjWThJtFzvQ05yI_I1B_KSpjiFdcUlnwre23U
FC5FzR05bRwvJl5JluOWfby4OEg6UT_lweRKRrJjqBUA_g_xzVulzHlgcK_zi5_gcTGpdqhe_MN47z7xJLFFWXfBAlL-kFMglrhqVjFq7ELNhDJx0T-k-5SF
TFvTB-cRZsJrOaSDxSpVWYWhjfsS1Y_NBrbJLFrj6RY1P6LfqVtopepl_H4uzykbUSGFcFpw-3iHXlmDEsRG3zWY_TaCty33ZXls0wxs_cA1OJzfI-b-mA-_
_TK1R_ZDoFPBGjlzguTWPFjfmDyJ7R04u4s_AByJhpzh1TWzwvSDiCptwxU4s_F-qXNLn_qD7VPfFrr-sY35jobgx-l9_20B92i_HXcu_V3SFMZB3q5Qkix7
Gl1a3WO8dip130LwEFUUpq62JdWqzyPpC62T_2ZQEi-VSOLf_XMNCBFyX6jutHyDJ6HcZnO89l7_gPv0_bC7iadpUnkZGThyDfHijryhAAO5rDJ8hrELjTYl
cNIRtpDpWs5ETdj7qW9F647nb-t75eNVVtLel5EnABatX3d9FvZDl-x_gTi0d5Gl3EAl-DlF4LbWSwtfs6ymIXhP_hrnbKE_npZrt5_sajxMVRYM8t_2ExHJ
lziIQ_jrtodem5_n5kRSxr8aP6Q7a1SgeApatZ3-TFu3mMpAvWcsSWIrJvv0HTRmQ7m1Z_Ufz_q9TsXt_HMtC7Vzk8dZMnZS9V8D7EvJ-6qYy9q197o6mE_G
B3w63N4GR_0tu3_-1m
}

sprite $ing [128x124/16z] {
xPhfkjig34Kb1iNO1ht_qzx1dQju8mBDkKFNdqvyPpjc8GKe_Nlv3UU79FeeKjMBCtn8UjElr4Hl9ZVzWPReZOXQMdvpkaNe3JmKyA1V2nSrlEy9U5S7XUcN
40urlEy9mga3x86M4ayTv8oh2-r7FK5gEiJQifnrXfRNbRhtFu7e4cHveSKyplcYo6Ncy-wJPPdtoVSjCqKn7FFpdTIoCpdWSubleQbbNxJUCG8-Ho1CMhZU
dah415cwtaKjTVMQjmXycv40RMs-jH0xoBe2mQi9v4VzZ6aQ5NIO67w4Vc0VC72xpUUcTyJ1BfOSqv_z2rE8njRqvbXzsRqqTi9O2zlzkEVvg9oSD5xJmKoX
V3hLq9Xyx9uQVE9yRj0zZ3YCKPnF2Rk7ERjpnhryUY3t_0Q0TOBpQGVk8M9pLA1Yyg63ZOSt4VYdcn7OGRzxcwjci2UVqhXxXwy5HPCF7Kpa8rGrSEyjrUCB
ctNmUHd9snUYDS_JWYhiBzR1UhTuvCuyt88w_TKwU9Y_C_cRFgM1vcDeVEVWutbl46EUOMYpU_OTB6R6y4ucW5LYsP63zjd5c6SGCFtZ3iPdexC2Jb1zXXta
zYH_KmXeFiCEdchp3yKmQ3w33XOpMtVceGAh7SgTWnOnvZcKrXxYBPXwg0FGV0OSV1rsRdonWwyJqRlqE_Wo6vZ-yJeuJiFDnry7N-MbazO8jdQ31D1yvXmy
nj-b0eOTbDG6VnBtHqT_7HGATKo0v7Zl6JW8-e-h0XMFTnjs4FTVt8AQovK3E6X7oq0ryOta2Xp4tx-m0D5fQW0EslokXUmhuotGPvmEYhEiH5_pIVGPw23U
V-0MvAjJRWV5MTZRVVEfvnUA-Svnuw2KBqJlxQbvTCV-szJ17g7s19IX_9VF7om1VFxrvoyMVjvzrfy_2Iv0pPrV5fo_sGASlFa2zYGpfq27BpzEdBzoHLV2
3UIlFd_-p05st-lFtqld22Zsyyl4_OCj0GnRU7QleUAN3q_SZlFZrFqJSizquUNtRuPZ-FpvHDzFVgAhJQNkycu_CdF_Qk6t_N-RK8ScR5-SdqQ5hKlpPVZ2
b9Vaeu9L2HANvVFXEtXSxw0Oyw1xumvcQhtyr55Zoi4jzV85RpanEeaOyunxaA1pF0x7cISYE-O_apwOmdQraqWiob4nWRoKVhvGbkD8VmyzYRSI4vdywSjw
d7_DQ59Dr_3OoIyqWYF_ckM_G-aIvi3vbOO8_VogUcMtpuiTvzCWsPrVAVVp0urILdx-JEESldmy_zWzJ7Fcn-ktOFsTz1B1cRyJRoN9VJwzIFRbQmd43wKu
wPvbKp-DqeHxs45CYUVbs8RTct0GSzL_8PvmRwuNduc9fIrmpv9qYa2pR3f1edcEwKlEzp_0lFhpUu8MQHbHja5oe7y1l_aJ
}

sprite $job [128x124/16z] {
xTY9ikeg48NXrGJ81AptVzjRvaoxjqaaOfexVJN5yLVJGYd-kVudOOmUlVZCJN9TweM_PGzZeL0f7eOYdvNGeQv561XvOiIzPAPY-mfaOOLPS0ktKh5z1Ixn
WiNXeuR4YzBmwOMsrolmXM_A7iq26pGlYf6jIkXGrsBZGjjkR5fexL-1BFouMTeMsdQBe88alY_D6hNbxkzxXCRl7Cvvtjkdu1JlxcUS6M_lSy29Sdz_mJ7X
_NtYs63H5noQBFeUXuf5Vy8XMlGBZZYJFd4aslGT3YIRViG1slGJzWcRpOF6NTZdQKImQwQHW5sqic2Fq4p5vcC_01FDUEp8tBTecPjrKH8twwXnttHX_0gq
aHktU_BYbUVKd66VU1Oj-mvFLij-n1DQzXE-4zC-yPstxGkWpRRz06YqxI-T-uGsMFS5ocZT7w1aw_u4XTRzKllBfpXjuiOx9N2pH8sL0nXfpkdDnve-LRIN
zEPZJsy-zaHjFlP2vVykIIkxrsPkSj8gVmMTvlStQe7Yhwq_UW26Fdt1JsEV_e2VSf_-X9_Ofr-0ZUlKftwiVL-mYRtwxk_n_gNp-KVfqr_ma--y_c7jqH_n
Hx7lh_X2wliBDmvAu6QixXSe0uq9j96c1dotqD28Pvbcrhx_FsVi6kndJul6izTd1YCKwnbSS4ACPyz-1WNdej7iDSrWGDczM3zxRJCu-VVw2sgmplL-HXLt
LrzG9rG5InI8Jzl5F0hSp7CEjUQAVX6CooH8Zuj-c4R1t31xMdhTZrX9PWoFYyDsw7XYnXMl-n0-32WCM7uUDioUvbxr2pmV8X83yg_3GxWelEZdt_trSV7d
OTFiQVCdtt_0TUcqJ_br_XyNjpVkKHfdJoilvdyXcU0V5pt90iTz2MznLT__lFNzF0aMxiERmklrBsHk5y_MFuTtJIVzQW7lIzpbmMepjFOPJ1CSQoMqs0rD
S2jheP5d4uTM4njuj5lvjWde-G9cV4RaEyg0ZndYT55m-0Vutry
}

sprite $limits [128x124/16z] {
xPg9igme38O3iXF8-x_jL1zhlDVIziVMsBFSx-nGpSTfGk96_rx-O7mCZhw5Q_83sw_OkomqHm_ZkwpeZyuWo9Rk7xPl2VG0KGw8f8l90eYQzY83P4Cgs2e0
pHbObXCKIxSoiPo4fxiJxRTcuBgSujwqxEKAtIkaEeKPADWlf-Kejn4L4gtc34oHsydcHA9LeGpDmB2eKPJtEyO2lHDbm1g8DWtiUNKcEg3BciP_qpQjiFby
31fPqUr-O3XQcFQRhRo7tZF9YaIt-d44fjlzd7DkiiA1vL_x9p-JVc_t2n4qluOecr71xZjuCGGFqUaTLjMF0p2e-d4EvcVy0Io_jfznzfaftdk-toyAjG_x
SGRAJ_azM7vjVm7Bh-qNK7nkfBVM1ajG4arm2ThECxinifmaZOLVr3fFxA3uQFi53ABkjxIXFkaFGzd7gVbvAFjCQdu1nKV13p9GrlN34YGw_bPAwRAbwFhn
8HIjcLJzE02YgX-FtLJzk0J9q_uEYe-sNmP6S9f-koa-6wAcFu3br_OpA3xQVW75HzrlQ26h-JipTrY2ke8VKcX1bFqW02PjFmY0gEu_Jg_jE_u4bb_Rtz75
KgVh5tJTPLBs6_1oRR_zP_p_Hj7VQgqT9Q0kedhyWnAmq_QZ0bYl-MrOa5_Krz_Jx4VPfGF_C9lqzjPVmTctihyFd7-5M_mMBFxx6jWvvyo_A7bXrLpgmdhh
lU31jxQ8AhYoDNcC2gu_AzF0tKzj3CXZNxi3NaGLlAkRg5Fe0FDmx3qVWmRLqY_57ev1J_trjTynI21CE_0djrNDZQaDnXxcmF-MJdKmzZ3s0tyTyHiQmn-k
loS9XYQUlyyTRhvzByaIsGHkkc3oaJ-GYvp9-i2PpDp1dc9zTVcSFGKGUnW-z8UVlzpFc3nt9AeYCgUFw6M7J6SuzDUNXChFeELtlp4TnDueziZVH5x2hJyH
-Rm_1Jg9XtxU-gLw8d8Dnnucd_RFS22xC_Vpy6V-EIXnx67wANyHOLDs_KmVOK_u2qs9nLB8EMoAE7s87_UB9rEanxtyP-bJajo0fyzXkKocAtIv2DCbh5o4
Bk8KdtVMZq57rwdoCOdkeAg7lievGP_eDgQGJk8j_Glumry
}

sprite $netpol [128x124/16z] {
xPa7Tgqw34Kbzwxvp_OlayBd6Hm9S_FgNlrIjXiwZWE_B_z0wvs1duMfj57KJx4t-gGQ-6PiemFjMrlWQAJPdsJVSV0DU9hWuRLWfCvFQW4cOX0HNeBArFb9
BL2512G5Zw8B2IdwwKBxirfW6ebujYnRMc2vA3fQfTcVOrylovuUmoyMsdNyOg5T9-9QeLqd8J10Jgbh9NhldFCXLqaB7ldUarF70XNuRL0mnz0N50Sdw4XC
4ARGdApX0Wp4eYvyyzKyyD5ecD1eGX0cbNmD8Wt8TlYS8O1hz6Ji4JW4mGgKF5tmiSmoDwQ_B8IcO1an1dyzDnjSeUYSDjF7Yi95A1uwCzEVZ4wzMOCBdHBd
-h41wkP-I3HVktviGA0PHLPzx5H_te16CqJPLnZweG7kJWMAmkx7oIVQQ88LJ7_bwCS6U7a4eMpZ6gT52cc687oGfHyRaCKB88XMdtgZKaUh3OGTAuwWUcVF
KQ_wW-88OhIKuMSLuSOE7n3u1Id43Pzst--54PJfX7pVRuKHnAyKgNNq5tujYo3aHs-cpkYNX30pVC8Dl_AfvEYqB8BYabzyLcTPqoyV_qGy4i-VP7win8Mt
MlFCloFN4xAgHHFuzn9IeW-PvcXUjPRupU6O1oC98eZNpD4__kvu5R3nYeKN-FS7hBVurIwKjr_DGd_vF8Pm_Kvk16NMEetp2NglAthVEXXk135lYpCzl3St
xpjdO4OGSfCgJlJmlgh-FtILjm0CUwyOh_NmOvyLGE5LeCYFwZZenVunWffWinmlzEY5_WIVY4uiuwbUDHBwQGWVPWsArmKy0q3-004IAuAyyCWqZh-vhVTA
T9glX_3XdZ_5eKdrwc076H547T5sLPrPgk1GgTCcuIFyEy0ChMIKTjeVNltFYRtbHy6_6SiB_8hV_trnFzz_91xkQVzUVdaK_QW_xQkNIrGF-d6uXq4oS88J
-SUoteXF2mOEQ5z8xiz3_H9GKd3M66DzpDGH-vlWj821s8zmn7-lNpFEgwGqVlvu6AcqYeOHnOupf5Mg7lMLVwQkQPbMZZJHcROZ2UlJzF0QN8wnzJMukfD1
UZKLfcXwCGXpt4zPUy-lGGkDiVOMrs2eCdy23eA2dqN-2YmKCSb2Fm8FU_8syWWgRBrs26ZA-y50wIQ7eEBXsfbV0PSuhXlhSZRzGaFmAI0KAXPyRcH1kvpq
uTgPtm6VClgt-JD4RhlOG1E5RVpjTgs1wjVoTfi-yKUGCFYtcGPDXAfr3BHF_tQj_m187Grjy5SGeNxqryslgErZzEclRxUK1kRzxZBuGOYzy5VG-Orz_Dlx
4DLFV_xHhq1AlEZ_FZI2_bkGKqxzX6ylRhiVyiUauyVyqz4VuGxjrEyWT3sQxa_Tl_MwRjUs7mgOex_0BTIflo6u5B1tEe4EfVjD30Xf__xhqGytiMV-lSPr
2QO-_xt-fS_wPoiT_0hk4WH9Exb-dxBkZx12M_KNM4Aj-c4HGqieM2NG0WRMoNIR0F0p6n3X6HpTeMbu3Es24AlWD-0V_m4
}

sprite $ns [128x124/16z] {
xTg5qjim40JWaoocVV-tRLLkFRPEYSugVKEP7xA15HZep_MVijuPsiLKe2jwIth3DzNGmsp3JvgX1pcSDVjm-fcZ1tZSy2HBHGnuoVG4XgX8XCxeDhq2NJ0X
QLhgA9XKZjKJxQvNO1gch9sMBTW49aM7TpKhbCxd12RQELvWefLy1IfXkQWc9beHIH63AX2JEEDTbAPx1i8KtOAqoXZpeWwwqS0Wrq651z2r0zs-1WOym6py
-hj0b_24HbSqBZJNPI2wxkiFqlqFmcm1tVsauG5B7VS7SN8EBelp_UH-wBgmkNpKW5ew0ENg1-th3y9bVfcRVNf-VMcUytC5C4lpMyvrRWQAZFmbBEFhbynF
SujFiBPXMbOgu8BOudFk7xy0GIIVlmHLN4WXBCuFZFe9ZdyqEjEByuin4HC5T8nyoSE0_6I-enCipgyn5bmfCrlVMihI_dSo1rxyVCLOV2JpBUFhbnh_NTgS
Zul5Hs3_mIg0P-HB7WRNf_F3-UjVlF_GEh2FWZGWClwu1NJFv-lJuYEm_-0kGO3K-6SjGKeWFnz71BC0Xf4lUHucxiYtZFCkKlkFBZ7g9xR_w6HFk_LyPW7y
dlpZjFW8Z7_E4eGz-Usq-0ZiFnW5DAnykHd8xShNv_Sll_yult-5FUCFZEbNCZyHhu0f1DdvZ_AEyU_fkpR8Bq3xwKnl7VuW3lOVcNlXgUTR87oTggdxzeC2
K6VEFxZL-CTVLY9VyQyyDcS3a6pN0Djz-q7z_eFyymychq8cFCZJMSLZCkFyiw0gVlMJtJsXeq1Uz_PqqD6rklVwEwddkhUfWuhkkOUwjwU3ZiQgPFSu1Bl7
ekMwnsCnOWbUaGxzST3K7urfuehZ7bcNiw68_Z16IuxHFRuopWTGoG2VfmnlCH1fnZ0_0v-pbMhixl7fKNv5pzT08BAnOOGcMMu-icNS8grfLcJcTyMH7eoN
UOMVttzGcDtZQvpyej8mlz1BD2SVcboCZWvsz_Wi9x_vqVodwLLXwNdUbHtaY_IE1fO5tHDQY-bDHl1-P_aE6dfVnii2hP35gozoJD0EMkPmOPBLz0VuxmC
}

sprite $pod [128x124/16z] {
xTdNWgGg58NXjKbANE__j2TLZnMb11LF-cucps_OZLs2Vwx_YPsSmLLCvb-IkgHUkCW6Wzd29yLW8CTtnLvLNpWCCB5Ymhd4yulfp7hW1bvm2XMv67y4Ah51
K3YKJcoKzD4BxLL7O0exPOFTBFljNnGTzohsclh-PNdYOQREXVQg8v30mtdPjz3k5mGRIE9f0hwoF9L2dU7915KyMqRDnDDfL1IUBc2TS02iqnn0i6hc0ERI
sq_EMCL6QTR6PxOfMAFO8Zh1NvIBR770znlP6pmnlknVWrFRYIyQBuFRSVkpjtZMVXbIx-gJ9eslr1JvHS-phmIBhSJwqh42-IC_IRZ2LRRZzkVPO3CpPrQ4
ljjVWfCj5p_mc-Q7Zq_t5GyLUawyYR5r06Qkqn0RoZA9idxYownEhO-WNEilPxTo6VIKba7H0EhzkNNyzFiYLxnz_t9RbiPwlxG-VFJdHIuwTJ_nuitcRoLR
7pvwTSvMvt9gV0J5XluoRfK7qjJu269RVtanb0m-cjeUGTBJHoHdTFI9LsPiN_32Z-rRl61NF_NsmyLzufaUtHSycKRtDPxaxhxlwyzumj7zWaTgU9zuvCRt
5Hx4yNs71npVJxYJ2_h4dRcYBrZuA_eMYt95Fs31A_h4B_gQlcp_gxQzFsy_gSolWhJrLMXu4SSjveQ-U6vGsbwx5OSt-MD_uZQjUmxPRkdRmesaUPinwczz
avitOqp_pducG__McNIzzPzN--BPfFErTt6V-rFlJeXXespV-xRqRqH4jahwkM_ohYtXmcP1tViwibdSlV7avTONptRbW9sduZ8PP_QG-fevVXSoSA09xpA7
YVX0E4fksFqSkGFg1i_UDJFei2vVk_yE6JnxusTGKES6pTufCmZTFtkBV5u_O8lJ-XcRgBFwWcqirraK9r3-zlmNY4a_7mp4VUahRELhVUrYqF1a4KnX5YGo
GMPlTRNli5sgz2t90aKwH98PcZH895sjxz6YqeyaQL3uirfg5Dvc9bVw6KtKUZ_VBcOgC7pvQQMFHdQrNsxHc9T-p5_x2gtyaUTlqIxLxhz6eVow__ov_scj
xz6ZVEuRalas_-6lgFar_tQbdz15hVIDdmNX_lMVoGXCtXZvt4Sd-x6VdK25PVsp-UVJe3X-xYlqcbVclub5lxI_xx57sTjFs4NjxMCdmrqKzfgvWy5-aTrc
uCe3y3Y6Ou-YSHZjvaPMuH_WVxy3
}

sprite $psp [128x124/16z] {
xTg74gCu40JGLiwQ___Q2yPxErwCq1WCbrvbRMY3cf6BClwv_gTSy1PtiOqUghublTDVciN5NASNtU92djQwkoMTyxX0e860xrA9TeHlfcUQa1I-GXTQtF89
T2M1h74gKqcechC7xLsVm7OIENSiEn8uVIXwEggxMz8v_uL1sni9X7C7ROq6qBxGl73MeEtPA_nWKwTPIHqVj2rQl13TXgmmGLLwhtY55Tbjo9y-xorP3EbG
Q8R6cAMr4ZGcA3Tp6nI6rXVk8612fR66aN1WW6ldG_3M5Xeo6EZhnXjCK8Ad0DiKlPEzmf1E981jXbwLpYRUfa6wi86HNXasNdfs2c-OpWw5rccNdTz-ipnN
cRPlWsT5cHj64PisksfY_NaRWDLoSs1yfu6EBNgL_txGrs1URWi5KINcls-OpK7VwdX7_ISpk0xp-ItVdoZkW-z3axDA-Rpimh8X3ZzeQpHxbhRKwUbZ1ezy
VTObOQ6MlMaHJrLQ02lCptoS-DMh42ETG6a-FnDLnQiVYN5uoBJ1uIqIvJVFhiMzQxYL7K5Ac5zOb_hRXiaAO8JvxFRxzuzu5XKWolBvw2cqgFLb84RH4TG-
oJVidnO5wCPss8kE8FeaNxFjLpzBLyOpi6DD7yXVbQwEymbh_cX-naEVoTTOALVcUwpGbVbrT_h8ywaz4C-VBu0zbi_n_Ea9bAxDT_W5NPkVJydF0G_-Lyk0
rR7C5i28ybL_pjjTkiqL88ZoAxk5UnhD_DTDaB-CogumHKyTGQ9No8tz1_lgn16a9I_oDN-2ziM90dh9UxjbL5bC2XD7K96yk_Iy6_lyn154Gzr_8R_k7JvS
jQVdqsf7Xue-Ery9t-0aTMw-u-zTfiGpy_dyf4dTdvXFxF2Prknv-OfDY7b5dvLls3oNQ2VbHpoHq4dv7GjzKpvXOU_ALtZmT-NhlyVrgvlt7_sU_8m31Jnp
_g7SaH_mKxy-lu1Hb-Ttl31Nvoky2jVch_zr9XcBIN6dUn-UmW6Jyg1x1phOC4TD_rD38X5JohXxdF_23cH9SpE9j63Da8rTzdEWHb-N9MKvNyEGeIzJacbr
FYCfxFayzhKxkiVTqJrEtz4zpj60G_Vg-PENg04T-UA8ngmqp3U-P8D4vE5ISl1ySPl7l3hATqJKeOcMQH4SNzoK837ABylNZqvAzTMYi7lo3ZgqvMvMYe1B
_PV53H1oW_ujKOMeE02syKL9z-GTN5zgzT3xr-yWLuVxRvOhNaBPui7kSNqZtpxgfAcg_CndY-zKV4HlvTiK5JAHXa_9m_35T_0Xjx7_Na5d8kfXcNziyNZt
kBZT__4Yv_2vUZm_uOX-DB_Y47qq7mTPEaJZg4W7M1nNw6CHkFC399p3qoUwmMcCZq9Eun_WVxy3
}

sprite $pv [128x124/16z] {
xTc7pgKs50JWSU-Uzt_QDAA_Nmx6W5FsawAMtPqB79sXuD_h5-M2jrZ5DlwbwYNfdM-QnSDSvoVTua6UttMtC7tZyO307G7tKec2S6TwvW59uHQwSBFa5-ZA
0LdZKgPoK3LNBzfLly1s3hbsBJjEc5wAdhEwMvC-lvO3BnCc5-syCBbevoKrjsZdPOK3LELjCaIEjzBOPtapXLsyMyEUmDiPxEXyjs065H-0rmmtgoOmyW5s
wUKd8rxY4pfUqNo4VB-nQ0TNFi8llVnaNRTzDbTqNs-jrbh-K6jj_OeDb2Xh9NfhjC8tIXiNKccKkJENlvTW5GxGBfREFNduyXUlCSI4ojV6ogTvdA527ng0
UFr3fEy35TJuau8PgXsl8E5KdME52XBBns6SV547oiTV4YzNKE4BpU6aq0SgY3ypbUpHOfXB9BCJAaZSFe3999czmL7AXaAIISCStK1svmyglrsSbeCpQZVP
-9WRIVRirCvIKqVB1t-peNHkMYqf1k-TitznpliGSwcDcvQ34PQgEre-dy-hZxdojLvpzER8Ki_Z-U-KiSw766DAEQKKOmpUMQr6IcNWpyqm1oieF9rlXFAv
D5-k83wTtuNokJkVGldSdg-5yhamNwuWFfzVyKujo2VUsHNv2c_IYdo7Dtr5VXR6xyRxtutm8w-w_vSFBTpr4SrrxZ1Y-Mogctl-4ok8ek8LXkXGAUb3hzrQ
FlZyhsmidKUyc57f1iyQXU-KDjR7qdYScdZjrzjVRtzobby0IHLekOXwRvybXFNxs9SGk-xqRmeN28zzU92BHV5fNUZfkodXo-FZNo7pcjbxrnRCtfePRCAz
ugeleFxXsLipWnwljRNVtw6Ucxr5CwYmppyqUsjcq4FMripUkpMpzqwlcRrtZXA7xXLq8WqwINOOIZIEIdA-yIKR9ARj3qUaWTaJLJ7VaUpGxB0aQK11mWWn
lv2aHV_hFtOuSVQ6Q2c_RQUqCYEHKLmR6EIa-Tlo2mbB6YNEtgXqyFZfq3kyTBx6LVdw6tGo8oTKSVR6zRryIx9jOm8ddFwAK_HklarHRLFd5GBtu2ItT_sz
Wjw6lWYTfN5M5ER_48Vpwdn-mem-crynHS_cOvBb58rPaHCivXMU5e6LFo3X6fvdT8FB61y7EOr_WLz-1m
}

sprite $pvc [128x124/16z] {
xTdfhhGe60JWOj_Vkl-hdSLyRT9nf55EosnFSdwNVIW10VzS_rCkU8jLREEcwYNfmbspU9WJlX6B1taUYLkPll5uG617m7UfnCsQ9r2P0vB2L-Z2pPedq9KN
P8qVPIelgkQd9zfLJs25DpMBQOuJfYT5prdYLgPl_EH4EozCJhJpmkH4Eo-fkObsNbOOe2g_9a--x_Cq-Yo_JA6BtzRctlbv1Xt2tOeEAZu0vmmtoneO-G2x
TFZ9Y5DyWk2CvYC6zXjhvk3AHtYSu3FgxEnJedVM6AEr-eEE9ACFCUKg775pxQl9M-r9XkEYOVSEkv3RlHaeyLps1XjxV8FZSLN9x77NXb-YVNz74_wabDAR
H58Vc-mJJ-GhmozlTLM6f9JZGBTQSlHMxpz501NaGW7CXms3zccaNrAYi_i_AOmN87RM2-KBBtBO61bTWivQM-0RRwZkzAsAW_MBff4KtjIs9oWyaC75nyxk
n-D91GON7mCWpaxrVcm9AYVvi9Kt5OEJV8-3pbxPPE5baZGsVcW9KlszkecL5zIWkmFBeSLdorTlkqEvTlYdplBLoEApvJDfR1J936ZhGyobjYR2Fub8QxMa
6BnL85dmYybDAHM6bY2UvfCbwFELJn-sq38mOdayVzEIJoJznvMtajJ6Pxcs1p7T_5roHhqFsdk-CfLZrCY7R_JUy-3NO7ld2ibWdVE_Ai63d7CT-Gnkt_lQ
zoDVGNmwNpgBpnFv7Fdo2SwvR-Nhm-BJwVzyVdy9ulFv5TYf1Va4TdP5li8khSXtsCcA_8mTL-GJBwQNBvnGUlcgj_ZixwXfaqSjwUD9REkVLBZAknAWvED1
74_5stS29MWXQL5uHWOMdxplQLoi72CbsjUmIkMvaNCN2R3xI6WRKcayLNFqLWsV9wcnOxzsEF9HaMGA8Mv2yDuPUP_IHvghH-zS-aTEUua5E-MoZEu15KUq
v4rlurjU0wfio8qZhXzxopR2HkU_peynL-6eF7VfrMej9UTIQgrDfYuY2X_GgvJmSQNpzVtyBOJXmrJlvd75BMHUrBrTMz2zDHridTlFbJUW_k7khUcWnxcs
zluTwhdkBUgWGfzVrBrTVgHxQpgOCM9HztPwKVTsZXqEuXLq8Ws490M65AUW8xiqHgLkll4b6oGc99ACI1G57otyPFTsjPVlI0eq1POa3KYFGjBskfjmHI-_
SCkIxOy2Hof5agt8PFTskfFVIDAZCYEH4Pa2omzmaUlqZrj-8M59eyZsCL_ZglJvzzD119wVVx_3TRKx_WP2PkI4odtyKvlete6SvDkjJfeauSoMx959kfDd
hhX5d-NR5DKMIAyGIBxUVpVGlTaEEZIleFDh8zr8zkS_ZRlYUV_7ETnNv_CJPiXiViKKFPkFIPPJD6P5Jh2OLtXR15O-GCBFyBn337wCyV4Yf_4FyB_V0G
}

sprite $quota [128x124/16z] {
xPc7TlGg38GbUjVxl-qzsJNdjpSBW-sKsxvJqd06f472BFrp-H-stXdwBKoL1qNzYdeJwLH3FunjSg0P-a6SVARPNrFlEFe1l4pmzBrm583_JlKa2qIcRq5b
0Npd35IH4oH5NuhkwYt96aL_VQ6LR8cQVCiCSA6jZll-0tnbMRPRt6DV3Si9clsQKbVf3qc-OGQeqFBEYqikl5-M_QYi1KrHJk5l5zfA1-Gi_cwXrQ07GIBV
AhIHTbIvGc9QW8ky8n_sv4KIGUnxTKCxYbn6qHmZxsYETcYv0TEK5ViakK45UnxtL2Mtq3IXoOnYY0ZKdbiUP05KHtrCzaRp1qhRK6GT6gC5qZwaac5wWKs-
xy0W2sHD0qoH1Smi_P30D44bWGGQil0iWhC06erGCgSmBQ3RLGCwcM8FTajDfC-w1erjX6lmr3vrjtXRTojHlJYixYDt9VtfdSVuAEQPDhZEqdYX-eIzlmRw
VHYCvQJteUEJ_rnAp7kJvDCLA4Bvrx3ocnD3nX6mPtllA421YBYC_5tFjI26VWcoX87bz5JpQOCCuUsbJXaWW0F3tbJDQvNnIT-TQK5rblnE-LEBz4A7g2VQ
o3HNgazvztoTUCNnp5DjlVcOBcjt-dKOtTfpsRzPDg2R7LTpzvNVUOA7Reb_RBZSWlB4VBexonrCaGPFn9t9mseBcYMgRSbjqfaKx5eEXN2n1V6aKhhH7-f2
duzh1Z2JOSC5U9cH9xxcfUQJneLH7OCs4MbBBMZYlZ8k8Kbc-B43qv8-TAQHAPC4h3IVEjCmFRZGWIi6yEFuvPcxma8hB0klmNKyHWOmTc3V9RW50GKGdI7Z
t3RGV42H0-xeyA81tNY81pSP4Lzsu1QKnmjCw9L4LNGKn2rerdkLKjgyqwYpv2MjbLABBOZX23KxwIMGNdW6CL2VPblO0Nl3Gt3y3NsBxbtgQlmZZ3zeGU2K
ogpAP7xy_fw8cS796htveClk3DxrmIc1qQqhlCjetfYmre1d_gcems1G1ASj25Olp9KUtT1hQWG57cANNiFD_APGt_sm0VoP77h-AXNCNu7rYrrA07eShP_1
0jGjznE-XsjWXbKk4K1q4xxu2tS2WAxXcF1T8VWxVljXy7UG0RV_9qrMQ6rVNTAyDX6ou6wBngKRGBk5NCzJr-Y01XVFPOiNd83P5Xr1zfcEU31mTv-3Imx5
2fojwPMqTbkFEyuUvBqzTMLi5a1O6PrFtJ_hGP3WTDsvpw0rz4gI1Tpo_pk2vnjb2RSSptKFTldr2N13yJdXmR8itoKOTPspdu54EO5ZK216QFbccEOu-LOq
8P9y8uumLQuHy8E9Lf1BD5oRAosXv0ePwpEjOUKDMHCxOILYI3vuDDVccDWK4RDr-sAPs3PmumM8xme0XsWrwOD-O_8fC1Kfbdnkps6Uk07l0OgyOXw_So_w
xX7qIbeaFBwD-cDOf0W-HppjmQShoel-LZ0rjKs_1yi3xvtrODkEKaVz_bj7fUj7_RwC4G1uiBxLhzJrywRlIQTI8ZdWFKoyiFwUaFogR-ayPPH_Iwr7X7l-
D__LPzmyEUWzJFliVqlwkLeH__H_UipAVEYdBJvI-QXV284zc8byD8RqnxSw5s_s-x-A9DAXY26NF6VY1BntseD94Rld-kBZMzQz_jdwp34dQPP95md43NeF
4-GLqd8MIzSfz_KZtQ7TrIzq2tLNdsvYv1QAxXBa1eRka-KoWUWt9n3fQt1oXQRfoz0kdCGg-WVmFty1
}

sprite $rb [128x124/16z] {
xPa7agGm34NbWBFzxt_RhPwecY2PeJMXQjzc5zklZJ-I0Vgx_CSTEKNwAUB40yF_Y7tXXHdfcpaMm5cHlf64zwpZH-oSHDz0Xa0cMro5GhQqDsnG7PdWEnGi
lu4VE47pT5V2m4b6k7UX_Qbl41TEST-oV60RWwAOS9Lr6Djraa6XFKSsABIMty0rt9tgJXHQ4vgZ3To06UtKzJv220KeuGQmGdWUS4GKyWgUY5oOmi0DNi0y
oKIySZnU18bk08k83z2nw96f3HIyuaW4Z7Wd_mHZgjSyzq_SdK022upHE-x0MjiPT3QPp-08_c3grnDOm3cScmR-g2m_Fz32NvIhpzg_YCFn5lwHKiTU09E1
dw7Mu05mSemB1YHb-JaMvtyOL1yrVnoXzt5whJP-HnzIONZzSGvb-QtzJLX-nRz6gwyi09Xie8qb-EK01DK_ioVYp0zc4yeI-gyGWABuLo86ymkVn51Q47Dz
lFyOZdRzv9Sy_tAw-d2BxYStnFLVQlDvotWzBhpouEzimD4JRab-QCtdxVvZENhWw51eWQMP-TKMr27aBvsuDQgicZ6_re8W-EUZVcAB_dYqv1zwzU7-nDhp
zXbehF_f0OYItvzy4gGVxxJcm_SVy-tqoqVKjoS07Aq5gGlA5qZRFKwscvuvzuroegvdEE47Es4iVnob-R3zXutVAG-xUFuQ__Xz_vJyGMa-t3_OSYf-NW70
_5eBWkH_zDMJEsml-XTnlEoFvxR7aoyfvbpG0fXaV-K7wOITSkcbvlDs_-7PZ5GENb21jVIx82Yq_HSHtRD4i_MNMf3Rd1DHBAs_WXkB3RGIs1vGz4DeFeya
p_PnGTz_SH9KltlRVEJzRppZJr3zl0Mj3J_ojjzLw7x-_x3Znpps_7a9zzyCrdm4FsUr8pZ6evyD-C1a6avvqv93M30aiDDe0jz_I2q81kZvmnAQZzdp3ywR
wcFt_44EOFefl_yTytT6VhR_a0lGKln6DA7z6Rn_4HfW_udhd_UpzVt-JWmdx3zi_8k84solF_q6F7-lFz1RsiV-Ncu0A3SwJW-KbBgGlLVcH_xFtlwkfu6a
3qZP4pEOASF4FpVVVlO9Z7O3GBlnRc3e0qhs60aMwDdZ6RGdqUTCcDD8mC6QII81nZYIITRPqsZVcBth6JnedSoUZfb_qXRUokzeZyF6xscNkYMEr73Gp8vy
FPKzdR7XJx5C71H3oOugD2gTOMCsyV5h101JpyoaKtZTtnxyZty4DGPqaaFrZqV_PF_IixTFrVoJvJzHLz9odg7vz-TVwIki7V_ZnADuyA0luRVy4S2IZwKl
ScpvOosEsjsonoax-TFgtq5VP-0obQwmS951b_2u25qauXAUhb9mWKZNwVWoXUv1Du--oJt12dGtGYedEJpz0Vxp3m
}

sprite $role [128x124/16z] {
xPc9UhCu34LbuttHVV-tdI_bIrf6ZMNYa5dFluOkfyGNIM3wv_8_niVWwA_2TNpHx5zYPppeZZwCPnnWHnyaGCB-mtP9e0yGCI3IjPWCXNYblM22REWIR8N2
bJ-1RJX1iVHMjeQJjEtTXVQl-WaSunJlBSiU2omNnO1Ls5zirmcBXNQTk5XerucBXNQTRDOAxJh5q0IcuG4p0F2D_T-N3-mKKl77puxt-09CzFC0OpyGr0FK
yC3I68TltBfVPjdG41pzMmQIkm6mkp5r8Ey707U3yOEkNFD7VyVRsMW0uoGzLepXKZembq63SpH7H3PXHFbp9HtuD_o4UvySSW9h_ha49aolFwV3zt5jsk_K
vTVzNVQqhKpwatBrwVxgw3TiuXa_qpEiujTdsz07-LS36AHVMNQ9gz2mz8I60oL6ne7cIMShhyv365CsUROfvoZEnoHyKxSjuq1xhVgKfzMwRUCk6d54xNqx
oNiU-4t3Ww3xzGgK8VCty5S0d6Fg0E3F-Bs-_Be_0iZVCdF2N_Jbr_sx_c5Bp_pLoWQbDX_Txt-USmMwz0l60KYd_0ceXy9b5B_QWZe627y1yk7AiS8lwk-u
1M7Dlytd3pneFdB-a7vhRGLQk9C1E6kd_L2QZxR--1q_xRSag9_q1nBWa_wcL9yblvv_G6a-wtu5epIVn_oX-5lbER_MWg1IvITtkrT2yKs3d3-E5DK_oipn
CYhI7vNy0LhpaVC72t-ZBxpqPzLlH3VNyWVXh_Ve2dzJ_PjeFghVqPtZEvAa7we_YULN_L5yTjuRX_1RYFbZt8BiZByAFrhm2T8Ve2EQZ-h7TFsfqB6Y-QZu
IRyHzt_QNH2cg9F-03r_QEgTZtp-OUVyVSOFqNpKzKUUyZjC-OreFgeVPiRVX5zhGJpqopSW_8uLlK_ubNwg-R6HIbUUVyW0RFF-HXe9inZHVEJyeTHjoVR2
azYE4pWQOHX7vFmXJmMdi2IHZLVF7rWs7pb_IDZGKmfE-26gZvQ_dMuKlV2F0nXE-i6MVgNYdD_EdR-4dR9n9UQFqVaRrIz9xzWc7vHVpO_kbdSiowZzwHJx
RK_A_elI02iqHi_XRTRsNzGjOPwQFoHSVEh0A_wgt7qlxR_fVbRQnjL-GqVYP_sRMZjt__hkQyovGMPFqgNVylhkSnXbRvZ1J16N-FlawC8CSBy1eDzuwO30
AFjV5xCfuyF516LslfX20mokfclZyyKO6XC-dBtr37hYXUn9-dN-GZDSvkyqXRtARsWEFxOvAW07GyQrk__nSe2bMVB87rpgO4En94DjzpzUAjcRfGs-Yzl_
gG0wRRi_K0F0e_AHwGm3Vm40ChYn4N_vZUKRZbZDtbe67sVg7gyyCUjl79t4F_Lt0FtXhpT_fwtkQDcR9m_yylojTesUfmtyCFVrnxx--yBpGlOaFF3lCMpa
xlbF0DWuPUVe57RWlr_m_N7zXzlBkf0zYN_ktmkUxpFrpzAh960TJw_Ji4oc5HYBD5h2OX5Qn649IwiaBE1edOgNIVGEwkNHl-IUW3Tw6rj89_6M_W7ypny
}

sprite $rs [128x124/16z] {
xTe9chGi30JW40G4aTp_jFzYRu_3T1UeuLlV0rXE9vEuqQ_hB-E2d-X7cLRPPFuXwKMUrea6SqLsoaG3UQaLDpYzvcc081y4qcMY044pFKc3Q4W5Bm9edW5d
wP2OBcMpTChswa6hTWPuq7QvTYmxQQOm5BsSLPnoEkOL1csVe31e-mI5GTidcev1go8PQc2og4a4EL75QDY9Cb03qRQ2_tbrbZueWYNB3ujiLjwPvCRpPbgR
Uz08LkWbVVkRijouxrkQthE2hTtvjha3vzPyS_Fu_SsEVUIR_zJv4oe_plVIhCwVwIqPaL_e7HwIB-UkDqgCCH_9npCuomLmlWVbryxF1wRFOld6oitCEqas
XVdBq8in9ldYmEwhJjBJJlpQsxP_1qOmTBloZRpdkijVdaEFvIQOdKU-sO3yr5t-qdTbn62LWUMZaOyRO5RDnojerSalHIfpx_GfrjeWpQmnNCqVi89O5Bp9
bxRbmvriRirdgYpmB37Jck-Roa_TMlCpE7NjV07BHo4VJA2ecezNa5oP7xmFd_EJQZuJcLq-FBPLpSSD44RdMx1yjFDdK7xj_0AMp-dy6EDMPsCiFhY_Ed_J
_YHg6P_lGVcrytErV1JgttWHF2dazpm9Z4FpwnLKXkRNAqXqyz7XxTNvASOaxGqGBikFFGzdBBhpKNvhDOFoQ-SNkc6TVAoQFXhrnmtehyi_z39cKit7Vx_v
KVbW_6hd9x3-jFCDkFnHpW_qKiRdB-3kMpc_DDn_ESMFDKpBcySbTbdEl8LCCb00pn-LBU3XbR8LlFtKPi3cLcQfCh87FLL6zc2Y3ypOtglPeRqtlWSj8Kct
zx1Lj_SmtTx3M9IO2zUuep9H4fcPY6TfmTGgjkJxQLx5aulHaU_gFImBuczNpRU14Pn0aNeqvAVRuyroeFSmnldvVW_lOX6CEZcOVviJYslwG9gfLyJvTzaJ
msxjbr5-LGpGUxqApiycDUHdEeHnlZ3v63rOstIGm_abuFd7TDGi5t1qN9RJ8frHvAHCWF8kffCcnU-TzNjmelCMEMocAopghQzoJr0iNSRwkPDZ-WNyzIy
}

sprite $sa [128x124/16z] {
xPhfTlmg3CDjra08Ul-dlVlEAP7-CsdlzlkSKp5OjOt1_hdyZ-TQadqLwS9FZF0bwXE_SINxPFB4dvYVkeA2bPa_MNsbs2TGiQ7QitZ33VL9zGw2vlO8uGJ1
Koi80m8zs5k90o8ZlZlHVjKAqeJ4UzDo1iq3IR7WLMP-I9sdF91eDUe3YLQZgecMP8Ab-ViJxLNCoWH9ToFm0PAHx2Vo04cd_j_r51yxI8BjIQ2OXzkV20qS
RblOi2-mHhXiH-N2li8R8Tg6-M9bZ_qb3peRzXNU2Blbos5dZC0xyD33hXiX4U7dmwuRuR0FWHvstGZJFY8m2-RnBXgmY07pqiwpPIARS3buIFhUxefx5ViX
oR1XuZU6A_f3p3xfJXwu57s8jIyHiMeRVJO3DK4_hwRYzRDMUnDZrKFGxrhnISnQBq4VMl59LARQw7C6E0JzIElpZhu-x_SVhFtu-0z5VzfAaFHFql-y0Oka
dnXBLUKOS0hww-VL9FrY2z3q_KzsFKtJ7qhhcsxFYTr4VIW7htJJvuvaglvgbqReByHw72MOwVgP3p-IiV3jV1VqymFw88hFozSA3RG1whVCZa8kjPRazW4d
Vmo-iB3lhK8T-9Lv5YTwj5s-neRJ5igotf6rOSPSYmzThIetQNNi42QjJaxZHn16MO5r2f0Pfwwfuk2dmjXoy3FfkDYFAK5EpwmYzaodXpd2r2yiWIBsAlEJ
mCPEhrsOxtM0TTLa_sZ4BVHIkp3rZFnurkdB4-D_LTVrB-9BVkeQU7twosZqKj5K_G7G_ohyt3of7p9r9O2Wiv_IMmf8TmwHoXGemisXc_3nHSMraMbgCJLh
5vz4KJcbknW7HxnD5fTBzxPB-gLgMxoJZ-3eLFbRTpVEhRnF-Ihir5OSBc3bf3FFsjPFSBIFQ-jXcln9jwgholh-x8hYLixb_AMPnjkoBEdos9UUNjstq9Uh
zTKO_2ranvvrgosq2LpLzRSgbPW_KgrxYco_VpikSj2C-D8ZfOkz_UHVKuGE7d_7Uvl3MNN-1hn3eRFlB_XnoWM9sNCveT5jW-DfBjiIyJ3-u9iltNkw1vz_
YdRXCRenFEWzYl1LtbFgs17Cml7pvC_DysJQVPP662ctbgq0m_nebUWwY_4CtF1pegWPQ740QBThRgQ06_mlltTO5RptkWSFizmcVgH59d6z-ztlcN_fEQh5
FaQp8dhlTG-EOW7ukMQTU_riEeD9f-FwUQUgbVTuZpiK3U-_wCCYWCjt-iD8U0y6AwqLYq2oqgkVvftttkiUdFNN_3UpMnmup2VfFPu32hhtT0_gD7k52G7T
Uy_NOdkH11RTUyzxCDdhdFXc3di7v-FMV-HCCAEzZLWEaHpi7y3_V0y
}

sprite $sc [128x124/16z] {
xThNOgoy3WLWoRslzt_RapPXSum54-F9txwxNSAQ8bj6XFw-_iFMEqE_nLHyAEfNqXk-LKClPXjscg4NSkWr-qlf6qSlu27mj1P7dF0hqnCkY4nBg0p1wbUW
2fwG5DrA5pofwBitsjzw1QRXAVTkonOJfZT5XrdDJgRFSvCRxJm_kT7EyvCRxRp8SnljlCHq0HSia-vOxwsMabECCGG0CRo9CQLSAiufafbXQad1cGmOsZI0
wPi2AYjjN4YbOO19X0CbEasVudurr__FB_J09k98VNhDHze4m2jjZ7NEUnyQ4DvuxvspnW5vVwta-bBM96ZOY_xnYjNsiOfQpT5RpKG9i4GwFr63tB_r1XWN
2vvM7iLHi4TZ6djwiWTKttKHiGB3mMfHlk27ikU35Mreg0rMgtOPJwavM3NOKG8DZNUB03ZMreMOSgaDlTPgoIbwPmjWX1sjqOWwo6_PQo9A_SR3h3wntLTr
12ozqw7aFXyquexoFtUWjb-u-wkORk57wrF5covVseFBAFzJApa5xupHQf-lWS9AQMETZoatR8xo7Gr0pE-rBnWhIhdkx-WO2_ctadlV-docGt55VZau5jYh
lLSpJ-HtzIUt88RWrdn8pMUl5Km9X_aiD9yzGoPM_509QdUcaLjG7TuwiV6fuad1CBrJ3Hkf1PqTsJsGGqovZZQSHmCowgDT27EJ9ZQVJQRD_kp9t03zHIbb
z_yve1hfSnMRp_vxyWKj1wkvFtlJHdSjg9Q6x0PdMaMTFFXl9ZOyvE2TqKfnrm8LK9JMrlcudL9hq8DrxQWZtAqe6mxhhzPQIdtJLqHDtd2thmWjY8NyJwoj
3t5t-kaBCCNWZERJA_VDHyhliTBlp9lF2cGQuKijA0hvCxPykGNXjVdfb_D1Utfvlbm0_jNvcdRgydov1M5rljo2rClp8JUVzVbAQZvR_vjdBao5SQpG3Uhv
jHa3rT8arp1mPUeNGmsQVeobOIxBpMURFsdhhE4dausD5TjTjTo26exfFpV6cbFmrcWMKhLnFgJIklcJt8BGa-TFhTLIIlvKtXmUYhDZQQ8iD9y5yoUX0BoG
pz__nREspe_dJxL-pKV-d3-naA-x5IhEdsmtVsBrWGsGZcuKp3P_4biGDeFvKnBdJ_fq_YIs87MIlry1pWxcJreRwy9W_YGLe97p1Uq314LhVpQ7SNB-EchY
_TyuX-A5-ItdUZg7QwlovVfBM_iJhCjduVYpRFwqyRHf6B2amotp9tcsmk9hPEEtddhLuzoYchZvoIsm-TqPEM_jvq1xD22rFOBWS7xwaNjWScfxzaZVk09c
cpyPeEol5eYKprBlsqlI8WvESmIi_EnruqugrmldP44Etbcj5NVFdXcewgi1dPTAlcV-tEgdlWV9glZqSpsMdd-jfsaauGKSZLKibqZ0MAsIIA-lFPbRNtko
jBxsP7LzxSdMrvvChQyzcSMve8XKm9jccLJ0EKLNnGk5P6Eqv836v88XDr5xlO8Jdnk5ju2Z3C1GXIpICt1YUp3DZ3SrjudQwwaBv-hO03GokEBkt_lDbeXC
HHNonTgRhy7YI5ry_vQULt3AKNby_x5ErbwlOQXmUkGxIW2iz78BTMPhK96BqP5-h7-nNXRyxddpr_S_HJyLS0DBFrSmBTACXac5fYXCeaa6KnJD2fXWQ5wU
cVxS8Iyl_INt14tJRRGBJxAA_WR-ypy
}

sprite $secret [128x124/16z] {
xTg7zl8e50JmWT03Tzx_QRU99SQ_IuB2bkztkfpZM8ORBFZt-aLPxmncCOL_oNfAkl2c60ncXHjYC93ZdjXvwPN309vlU7oNYgncF0ALs20gV8LUMSru13hp
WAJnKKlcGNdvzA2TzGYCyAHYqCsoG_TGTEmbTbvwvJe7RJ_VEMZx-Sv1so-gla7RBoaqK9bVaphtUp-Dzmo_JE4jVblfs_Fz5hmXhEPqK740_6pX2twvyhom
IwDqi861BzZTvj3OEN1_1Z-I4Va1F-A8VC5FzC5yPPptpkXZ-MmuRpJqpyR2If9xqx_s6PnvJ8dUEH_pfyv3nyATHgLSvW6vV_gmM6oOt3-1JDSGZTtNmDXt
chDiPJlV_j1vN4zzRtz2PLCXItAeGbS15hOHzVmLc3XSI4y10jku5srPZrN0u8N2Dhj7QssvFe2olJQd8mLYcxZRgnggqDNpcszvIGLx-j3coPjyB9JQeRKb
dzXpHqxmwlcMjPuhMPhoDNRMBvonmu5B41j84yhVzO_vtFHHQ75g0fcn-GfFujXyYoSScvycvnDRo-XyXGq_Ed_1HXcT7x31K_ag2PCwbIzuf4_bAwddaQtD
_6ihe3kL7r_lfUtyRxe4hQVoQsdaLBx30uxFpoUElkhbYJ6UoYVkpAdy-WAKe_tRtraycOzGIi2pGmUv_dFxsVo46yx89wwMEVaAbP-Jlw0gS_83Aix95rpe
IVd4XPcLhvekVdwf2jiqph_R9T0qpgbLU27blRNnAmMrk_gC-Fxt3fNCoK-ep9nyjJ_-3FZzuyRZJZZSYWUAemas5WwciEKvr89dYGDvx9L9tHlVmOANbadT
kt63kpUdWmxLd0uclA46Tszy1nNUSvEwTvCcTE_p7GpbSFTks4-m7kxUZMQtzMM-ElsVow017KXId88ocIJ5gikD5cAG7jRCor_pDLh5NMriZ1QE50MVWa8c
HS450qTQE1FAmrgsyAjq_0qoS-Co5hmbtLzBWeLqM4aQ53eOShCMzgz_n17SK4fueRJyoK2e54cMLUYGdjRs-GNLcGu6m4RPd1gpmB1ooDkr5_bz__jTBG1J
MB2i5ooF-OLyNDldQrIdEvWTD0MQbJpdtzVs-HR7vVtmp5IGlyB9w_iVIys_hUtp8yuGLbcbQxv382dAiBRE8jVynxM0nBkCwcm7DLoC3ijbqwUWiDxslsND
VrnBM4BUTUzq1yM_cNyrVxjceTBfxjq4if_5UPdT8de8EsLqqUo4JePTD7e5TZ3ej_Aq0Cny016VuNY6BFYOnOM3hCQ_m2-_0m
}

sprite $sts [128x124/16z] {
xPg7ZhGu48JRERlV_salp6rhXK25_UCrbpv5hoI-7LpJPKRGFvZ_iS4xHI-X2t_ezXLxvMySRSQ8NV2q4TluJDXcxtnDeWqu1YH5Fuld6xAcdoFm04M_PHUg
eUMen1CqkzYUUP9krmxQURfRFEhcyGliZPyGresw_V-1wxo2f1uFslt_WUUbPFrir67MZcKL-KUecaP8_6CqJNTe_b4yOTH8ksb1Dihe0ooP-s0AZvzKAz-Y
pryIHGSwVqYNdqazlVjgra_Zyp0D-jLV1Babwe3urH-S_4m07lCR7iQUhgfUzbjGjZlywUdvDkVom8y2qFW9p_synM_cl_tShFwYIPqTyABxMfiikvLI6ZqH
UVWnZdkKhmyhUk1UDg9hGApqd1zd2Mm_ygiFSl_L0Izx-rdT-3LTeh1VyJ0U-nrTOdVv2oYV7Nu6sx_Stti75JxgTyPO7YP8Ja_p1rIGuRK0Vneh7wSdIOF-
FbO-bX3ZrnWB82_mL-J75QJ7_DfOQvsrHgi7_a0dt8tV-5GQ7-Wr1wU6_RY22l2hK46T9Jljvv7j5xyfV4CFHt_stdVerwXyZlxCBFHQKemX-11YohMTVcwh
X_a7_0wKpy6lAdzesHjrJgEDLQuuvSyZvMFbxpsY1sTNPAX3Fmv0l_P_BXE6VgHpKtv5Hz3izeIGJGhOZsUBGNvkNW6xISndVqofCxDJIl45yLG-k3jgjEhA
xNDdFllF8mLNK8L-eUOKlNT_u7s8kOXwn8y3oC3V6zzH1_oeWZJoLp89_Gl5Atkz_yE_2pli_mFbOcwdJQp96vbUf_m3vAf2ll4BIjlFtdllh8n3v1yD06C_
OD2FAqXjyACAielzzVJGZIiehlA7b5BcGN3vpFlHTnbN4B_Yjw1yTlWZA9-v_jVI_rFxtm_b0yy_OVZyCyDf-z7vBtb3L-U_SZx_2OCJIE60Y43Elo5uxqE8
kLoVVyTn4XZe9rlvXYvHclFxWS__GOSAv1ay_q3SUV_nyr_d8or7zFmtsa1fmFzTmDOwv-oXVd_H3-ll-VF_U07wHUyJQPwWelEFzEWKkJC07i0RxqRH0Tu0
ofRXhKGI1CyRgNGcyJOwNL7VofxmLlO4_LRs1CSRA2Iyai5EYBetU_ipQDvz_oNG7MvZzfvdC3QUeAq-n7Gg2xCdT1wbJFdDgcDKr4GwVWtIAklXx3tDe2UN
aYFFrL4e_NiDoJHEP0GP_eFWc2ELmnhGrXsavGqdySiQecYAZWlCfIv-MQ_9dg0OK1mHsIP-MSF8p68PKZrfySjwJVQ4o1XFLVooNfCzeV0rLULlVpwiHxBt
F8EQV4gU37Cc4-ltUkXzb-SPx47c7JjIMTRhiYTONa2cNoVmOnezeV1J53sYypCqFKCjVDzvVmOJ2QzaiD8AmbjwmVGDUm_HBaxY3Vq3-9_V0G
}

sprite $svc [128x124/16z] {
xPfLmkGu60DbntRGrlrFkvHUdbPGwQ5w6lmh87yAuTlb9o7t9U5JfCe_ME97x8r_KHCU9ZV-YvRm88N_f-KFsbSA7g2de8UNC9AQtccVk8Cnm4ASAN1lGLnu
W2dYLhg51rcwkmVjfxOWDHxYth6SUOMM3QFEi0K6--MntFCsUiEWTMv1c7WxOpWmQ2rC0Ji82srCs2JJIeGcqKo0X6xgjJLVnmqQgUaWQAHc13JBbGm6-lt4
UpgxNoTmUCAVvEdt-mUv-lp-XdT4kry7i3pZZ_B_-lr5ddw_Vv7Jn--dw3wlNq-WyIb_bgVVxvyEdduzIdWSKJx74Fx30HZiVbr1rUxN5KItNrTGjFjr08lT
hojejljr1T7jrnKK7lLJbu_V7sJv-Frv_-clVNaB09It3AA2zlkZvU7Txl9fE4_O7O3UxjUtmLNwKtr30ABukx2xWYZzMHp5A78JzbPGjFjr08lThvVLRFVh
2gBRhoiesFqw0CdkrnDejFjr1JMxNrSGF-6dBX-_FyZocViNAQNSl-3Aye-_I_sBnZ-eN_gxAYkexdvZydACuivtnXUOP0NnC_ucoyVl9rRI0tuLmF8fV_mw
zZzy-FoZ-Vro02U_NnVWxFThGNlUFwiR1R-_oVillpzilNaShFvE_HC_lNh-w6TMDwj-gdpxwIU8zry6PFQUps31UohjJ124XxFtV0O3DCMVFStapvwc-hEd
yMTF4_tPqsHAXWZ4WUpMEcxeo9O3ua19n5v6dQ4yZXc5u_hl1eni0ML8A7kpT-KjxZeZ-io6j2ufic0ccLHsHnn1-4DeN4beP4CcGo39EhVjx5tEu03aiQtB
QIG7JEkHqDpuwc3EVtuJZKHsWQp2Bx9tFeDBGIIPqHeAj_S_upWB5GKBEM4QiV2lyp_MExAddmekOVhBJ-GkhB-RI6Oi-b7lBHcCAEDOrbLO0dgIVwx_hBDt
JmPR_vf_9EUrhlJyYpZBm1l8EC_2ououGkD55YZyNOoB9EFtpluC9bndvca6tC5iZxxbdg1rk8sk30V94Ty0F_aL
}

sprite $user [128x124/16z] {
xPg7qk8m38GbjyGbtlT_snlWkWUy_XDnzPjA_OWbj6dov_8VZLiAygi81-uqzqli7LyvWhoPsF43FSWRIHZfyStsaIHlOCCBDh55CoPiblO2WgnYWgiWoMfW
RrYWEBaKtx18yrSFsb_r2qB74jUEvGWQWw6OS9OUZUmyoM3Ghh4P3DerDeD1kqRMXK5hGb4Xq0OpoeV-xwta3r4Q1jn47_0pkvu8hR6F9j-6duboYdsOoMl_
-LrEClIobnTqShbu_4eFAdwY2Wk_IIi_DijfZeKbtGty3JyHYBKoy3CjZNVukpp3BVkTzuxmamsOrlokT03ekwxv7V_Mp8ssHFY9TsF5NuUUOlrjCdqeVsPZ
ec60pZvaUbBfn4-yD_F-CLRs1NzaouzCb-fOy1Us_CXygHRyc9HqxayOS0j-9SB7qX-8e5nTVvtufyqAk_vZ8iXH_lLKRU0QC2tvmyhyePgbBlcbiCUNZJma
nvfVsiBxY0ZILR-KOUjvFoO5PVmIAdEohm7C1Cg4Vq13Z9xO_o8Y28IVWFMNN-p743vsVgO1jdVx_IHyhFtxfFoCt_aGO_1A-2SHv5RzVgi7ldAKv1Vz6CA7
zckgm4Y9h7-CeChxGrsxxD6Oiy9W_Q7X9TKJ_Y62bFIxYYcPz6C8d-cNXGw2mt5-7S9dulVWw3hu9n7KANy7IHlyamW2uzz04nW_Y8NDaoywzJ6TRraUbf-Y
Kdu_2Hzh_puflxM_JyB7se_9z37tgzn9lyhlVe_jrrzSV-cKFqGQJ_dB47ys-v_p0Ao_mhyHjJNqL_aEjVCVhuRV486Mrx_6ui_JNTQXDinFJkZONV-yiz65
2dAAdI-hJbBwkXlMZgLIeUPJr__vKxK9Ry4JfzGCISom-4NtW2YiEOXnOOdAQzARUk_Nz62Y0ikC8Wo6lKVXO8IUlUSo26v80B0x4RS3G4yg6Xg0A3qyRo0d
B7dkJn9pZfA0hhALNQNT_2dinwJt6DhK_vWKMmJI_TrTF90ksvMU-bKx7gZhDu9q92b4xp6ucNyNYRd_i2FPa8YpRIHnuaUD8X8E7EBh0o39GVGUHvxu0RGa
3bqS7hpmnsiE7ABqUod3Ds63tfz4V-7F5-svF-gxIK3JykM99FjDh-6flma1quDLV6rRa00uIJadyJUpfBAhFA__TVUUPoUQe3VhDio_PtvtvTxxEj7Yu9ad
MnmzyZGXCCnYEKa0pshlsVTWaFDKV9XThg2Qjxx9CK7tSXa-xOj49ty0__a4
}

sprite $vol [128x124/16z] {
xThbOkiw40JWMJ7F-p_jXS9XR-MeKYwSxszX3CgE8VZt-ary30xFuZfVDFEKzC4lkiDXVl0xm-6Wm9yDVoxzGi01aOg8lIHJiNiBf7125cnXAXMxjy0qtb0C
FfLjlAdPpnwqpze2D_YWxh3CSy7oK0nSDVnY-hgmE6ZNnSL1kouk3jfrMTO6xReYc22DsvJ5p_iw0vtZPW8LT-lGH6vdeHZShk2Qy01Sipn0S2dn0AUU_lqI
Bl64WIk6HonSR-oTmOr715pW6KsVFlijTD_E2PHvY5y__HozjzRgNrfhVN2zWeGJUat1MIFuYHZhOwwT4nufdr6Z4qmmFjL1bTmjdneCRh6ntQsWpWizu14I
nwqAsd0J7OPIGNFbKx52Edzfldm4Iznq1TMhMR4aJLSGBuGDyMmtfa_tU50Sl39TFhQH8pdSvZF9ucSdKBxSK5j8iWIBMU9Y9SbiO6ShI3jG4Yf9ifVehQZ9
DgJIIN8KByfGB_FvhrpyCjHxgpd54BntBxmF8QPIMoVVjzD-L2huOlxtn8LK6g-DLbAmK_zN9czyVtsKdGynfPHpoJcdb6BmpiYTKhMJvOCrThA2U3f_gEMp
Fvzw-UpFDqhvRCZNUuNdyvjQFllpgPVF_dnHosT_liSNOtk-Na5yHZxrNzgVBqhvRBp-_S9UbC-6wt-zWhQzHFI3YZ7vsAtvXVi_pVnpbne4jvZOff_31Cxe
PVB-NrogWpECil_A1PwpWf-9iIwasZbF5fwxZVxozASKzG6GJXs_-nLrIEmdskNFVl7eYmTzi0fF6sfFxIVwcyVpRo7BazRU5_r9Q-_y6kpgjT9-yjptNnPN
ol7NN-VNO8523g-zysjGe0jFMdlhQz1ZJAuzNT-NNp1ZMtx75BChNp37KsTVamOiEO90N9l9DvYLgSgllv2GEGIn947xE3zWNgDcm96a1HbGINRO3_Cpxg3A
OP03deHyEIDwViSjXfg2J2QKzoF1W4Oz7pTvQk18AsJ_ab_rV8ExCXKUOo1mUlyzxclg2IWPZQIydtzg-HaFq4-djo_90OLaWzFo6nvYU2q88iald_-kvM_u
xdbzxwcN-USxbNopylfsdSVZ6fTbh1XSrB34S14MEIunM9Mum65TNVkgvxgwVUblkISO5f_6XdIJD_WN-ErF
}

