sprite $control_plane [128x124/16z] {
x9PLcWGX60CNbu4_zp_jwhWmq6bPgtU-2XPu-RdyerpmTZExhVYaw4tiWYFLhcrtWWjarGGUjuZRphx7hs4FQ10Mbgk4FLiaK1aT9BMCNU-mPui4kc20F7Cb
cO91YfcxQBTAO0L3p5lB3WHqANgmY2FjF9uiMfv05YrF88kM9ockQ7boLm9Li1YPlEyy-bdPOM5Ksuynies28Ifvvs-FjAiOmRJyWcuagEEPAJETGTLlZnS3
pGxTDFocr-vlXsRm9p2YX-hlrrP25vRR_lhve189ucC_O_z4HJn57kVdxFi4Cla0UjA-nyl43Yw4lP6W-p_KPUSJb4RxTDntFa7xxLl-0_b6gPLbEGZ3iCaU
SEBxttPsAcXTe_GJ4h9OblJi1dlyjZ0SS9VtWlAEbCjI-CMpQdfyBizNOcbB4XGMhIi8U_GkO3Q2JmZnuGIx-j_LbOZs9Rh42NMhfQjvh_kA1CsLy0Cp4XxW
JIoXzWNuDT-kZbFsq8AYXFXGVatmEbXXLHw0bHnwXOoUWrre1eWqMGp7hStBwsvuwyOpwWfKSBdp0lOHoPmUDFiKT_rppDK25ir0UOdyaTtR5J-ifGYC-1W7
gXKpupo5CjjaqTbhvQIYFiWBVGZvVf2sDycQMGdoWHhxxvU3lY0oJ5YK47XFGulFyRQ7K7xNQjO9vpkSJ0u0pTsclCl8rFBVpUKkTSdK96gRmq3HlABhjrga
6U0Z9OWA_tPEzPv2gFDFyJ1hZp9d4UGAAK7Kg8fRr8Yi7-Dl3tACQTWiAq7KBKMidwwKqb2icaEHqxm4COC03m7WaS3HTpMy1Dt8HBja7V1JN4xX9IYu82tZ
kjsVoUL1HzfpIlNmlw7jQLs2iiVIwOWtDYlV4_RQzVyv-bCJ-Sb9a4yI4UkFCrRZC6A-unadGMoEOFXnwH-cZ0rx_U9840M_l6toinRAqyTPXu6qMPObA7di
Xo5ISzd-mP27aV43lBeaGOsm_lLvwlugejssg_kT1Csx2256Ee_res6EJ0wEjuKufb8JZdzP1Fb__hf-iJWepBj2N6IArH78pe-qDAWsiFoFwKxFGSCvYlBS
ficlIsdXIxhXhkntMJAayr4L07aAj4QsdHEzymCa3gIJTTEThQW6fkfVl4gbHkEcguyz_BYoT_HSdUPpot9k-qL_XEk4vFMEqJPg-FiJrAZn8wIknmSJtKu8
v3w5wfSOTC2tX9KTwMcxB5NpPQ7nb6_MLmIAnPvIBWqmjty71DEqBItVXMgB64I4OT8QtyfAf4hwtZPZQ_jNktQHn30Gn52qpUov_sd3YJQXQNLAeRSt__9A
E6bMUx0u6godfJuF9lhIqHxP8EIqjnYG3OAxFMWTTmr4UnaDyfEfre1j4A0aDY14WqHxH8D4Uqo3V7lU1gkRohtMsnuiclqH90h_1oarsoDeDDih698BsnxC
ATnWELxNdgX10q63Q4_JO6FvParxiAOWiu6YGNDgDEr1hsaFParxi8Qr9shGI7LGUve6Q-DDoQst29CcVMYJnrfPcAhjCpMbVO2_BG
}

sprite $etcd [128x124/16z] {
xPdfekig28LnrgZm_azxvzjZTep0RZppz-iCLcXOiXg47vVVc92YXs-5x_GFpNwJw4WlkeUlJ40wWLyrWqXNC7oJw2CHlWA95YJOYod4a7P6FqX0CR05MubX
PmQsaOB3mgEuHagQUxhHVgiCF9AAPzjoe7V0iANLxS-0ZoudRcYqEjA6HgiZRMYqEefHDDej7A8CJADj79lFEm_d2vusmzI0T1m-8wdep9dNIpfqqk1W0P8O
JEQbcVQG1eqyUeOHLqaCtEEaqUFreyS32imo2KMOOGk9yE-LlmSOqMUGuHPbz2ic4mlUvo-BpcI0dnPW54NthS0KBFRVRV2JFRW9ehj6XBUjknX11X5kuAD3
EKlO3EENutKocGoQglkCkteyxH0g4M5n9_5KmsQWzRvuqKSyIRs7iNZTScPYO4fXbe__7ywBUyoJ3bDfJb2Llrx2i_Zr0pXKvK-Ny3n-tKzKvkCkuk31TJyt
2lD1vMleU0OEZGNrTVd1T19Ik8QQOGBxvcAGH5JMK51XFcxrsxpwr5URero0aLzgfbEUqEzFLsKiY5_QRlsfsfjXS88NIMv1l5JQ_S2vtEpkn1Pas5vPL--I
7kSV4dSWpxMAl7wTDtLQtyPiovaFJlFpd7trIzQS1J5MCPvzjFpBst59cx4WHgZv4fv9mAvbHIhp0SXS-77Lg80k4q1YqamVQfzncAycfEO_68vPwugSo7pQ
9NuTP1r6buldnsrq5YHsiZRy3KyIEvk8p8AuLV5YFNryp6vymlua8vq5HSOdXet7-FOKVzodYoo8NJHfptRr_FCW4uq5yJOnTAwN_ln5VtKKZjo232TINpxy
M-vOlvo_ZisVYutPAYp8BxfqghKjhFDUnbYFwcGML1OQoPnrhRgOvIo8FoD1SPtGk0r63bv-K_rK-VYkCnR4IBJCapFYnt_8B2WjV_etyG0BvwKwE0lgomfb
wG0hp7kSPGTnwqcDarxcz7dvEzs0_DZDJVT58_lwQMY9C_Wx1pHJUHJP-wjXHhg67_lL-G6o0l5JvQvphE3E9R_Qun67RzXo-9A3SR4C_vTJ-xzubbOOoTG_
_BiWcskYsDjVz8dgN2MgxCX0DlQs0BbRk6ffsTSZMMxz8RlqwWR0S2Vbwezcq1vdW5Kupu2YkLyAyYjXbAxin92bq_mA0qPwPUA4Jv_L7YfkdiPthYHTM7Mt
K4byQ-aBtYmg7bvaxItaeRWrjB4q6i6QlO41LdjNkkuJUT6FnTfJQd0aBQffkgoQIWtoyVNQ6ucQhCjLJdhjwJKubqjIQ2_25Rq6xUtBd5NUl-irUAqL6hNs
tjQW3IcNe-JexTlQaskGGQazlGRTBVPl8gSzdaxRE402xQA324kRC20Zq1OiI2cqWGXo6ZrE0GtxjFUDD0XAmYRjVHiD1j3JzcgF1-aX6Z1irY1yah1NUpnv
h_PusbxjyU1UxUtN8Bo9twYz_Hhqy3wLFas69wXxfSyJwJEWWyTmCIi95du0VlCd
}

sprite $node [128x124/16z] {
x5c9bjim2BGaq6tu_x_jYrz2wjfo81klUqsxzp4Oq0nYfpyN_-4mHRYC7MPUqFqbxCI2-TkJWCGhqBT647aBmglO1V4xs1CV89rCxefGNH21gwn0SUUm-oOK
5qJWEnjGFon9eRCHFNnQQA-A08XD-Ami8ty5X2T8dJ62gzW5yGIXjI6T8BGsf1E4reRY349x2geg0jVvD5J3UJy7htm1-6Iyg84reP39gCcACszhQRIvqw4h
4Qj1ILA9_KCzwFJiUJqVD5PZ6YDesRUI7ke7EZ2p1dFSborb1F2ryiyu5ix22kGnlvaT2d5BJr5nYWpIE7uRUspo-UmC4Gpve-dPFMAP-OOQ0IQ1I_Ic1dTJ
tO6vHKWPe12NjOpHM_EGWLsieYBVKAOr8l4GtQm-58TMrQFmgoEmUf-mg_W5oQX0nV3jmj_6_DD8bD5K_ZwzovzC5kICUkNwav_0f2Scymc7zzA5Fnlrt5dC
Ppf0f1OF9kjgiQ2PTz5UR623FmZFKj8J5ahUO47UK7ueH3LAsdriF1SmD80XLzjJ9JRHaxkPlXIkebO1l5ei-YPFW9MM9DO8OPe0KhkRCA1M0QAw_6MR9we8
EGCMkZL7NuXBXDYOlV9CTxNwu7wTqltDtRGfzFsyyW1gyt7x_2Ml-1bedxzhVstHd1GxVzQcLMKLTdxG_bvLezhv7G_mjlc4-SbFOOb7-9jQrTdf3kg-wTpv
ytDL1JHOTnRTWyscsIFV-CjJVoi3KRHQa5rz10vXLMhmyKiMv4sJPsuZjdSjA5gkAbwY7y1kGSqo--0cCMuTfzs2z3OnJPuM0KbTH0nN9yzWGURHDp3Fp7Dj
gnugwqpPBGYqAbsMg1x3Tt4WrTlGMYoeQDiFHBeTSVV4xP5XNAIn6kPgV6TC2w9ScLDUffxA2pAaVS700mkotxpQ8s-HIxYle_paGYRvfMOB2WRrQmnICum_
p-TL8hPQKDAF_d3Z4CN4LHKBixVSWiAh0Cj-Bfj__54GroUqa-aMcb_kNU90pOcOMwebhsqSzfxVpQyMSTwmh0uLVLngutDklxORTQ_GVu64FGIvaQUxjaIn
vPg3UgKh9scCDf1KMfg6uq0U1QXO189vMnlGJMdm_9pL6rMdsVhZmTr_KtzkDRiVxTfLUaCn34HX6IyvzlvNMuOfToJdKo7dkH3uW-DFxM60MZTPBLsmDCgt
xU5pPTOkHkdLuxzHSqB0oyaOH5qP_zt1J8befwl6uzZHnmPN2Unzwre5rMHohwkL819hX_lg6_Owippr-D5RwxuyhX3x_lAI7jmAjIWCfllds-tXYJBrqG03
kKBkwjKmFnA9bRM7dRG7618e9EsP3E8l0X2mHzoRh44i9D14siCgVwanlJsxGQomnu7i1h58xkzsWtPxTeEyFRj1kptUOFgmU5lLsSDE7kUFi67A_WmIFSuU
OSNZx1Ms3NEyFQoDwMt2T3vxJWQ5h9p9de_18dpDmnxMnwIQG0u6HLdni8Uj7lQmvc4FwzFiEHaKOtcIFH-3MUmTGzqgCpeyw6DrQEf9ffNgIbQY_88kNGC
}

